### ISSUE TITLE
VS2019- Unable to locate master.dacpac during build

### ISSUE THREAD

**Issue by KaineVarley** [microsoft/azure-pipelines-tasks#10499]
## Required Information
**Question, Bug, or Feature?**  
Bug

**Enter Task Name**
MSBuildV1

## Environment
**Server**
Azure Pipeline

- **Account Name:** tesgcloud
- **Team Project Name:** Accelerator
- **Build Definition Name:** DB - tmsa Build
- **Build Number:** #4491

**Agent**
Hosted

- **Agent Queue Name:** Agent-01
- **Agent Host OS:** Windows Server 2016 Standard
- **Agent Version:** vsts-agent-win-x64-2.150.3

**Build Tools**
- **Name:** Visual Studio Build Tools 2019
- **Version:** 16.0.4
- **Workloads**
    - C++ build tools
    - .NET desktop build tools
    - Universal Windows Platform build tools
    - Web development build tools
    - Azure development build tools
    - Office/SharePoint build tools
    - **_Data storage and processing build tools_**
    - Mobile Development with .NET
    - Node.js build tools
    - .NET Core build tools
    - Visual Studio extension development

## Issue Description
The build phase is failing at the point where the `master.dacpac` reference is being resolved, with the following error message:

> Error SQL72027: File "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SqlSchemas\master.dacpac" does not exist.

I have searched the server with the following PS script, and it appears that the `master.dacpac` does not exist on the server in any location, including the location attempted by the build:

```powershell
Get-ChildItem -Path c:\ -Recurse -Include *.dacpac -Name -Directory
```

In the VS SQL Project file, the `master.dacpac` is referenced with the following setting:

```xml
<ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SqlSchemas\master.dacpac">
      <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SqlSchemas\master.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
</ArtifactReference>
```

### Task logs
[log_6_4491.zip](https://github.com/microsoft/azure-pipelines-tasks/files/3227056/log_6_4491.zip)

### Error logs
(see: Task logs)

**Comment by 20shivangi** [comment]
The file master.dacpac is not found under path C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools.

Rather, it is under path C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SQLSchemas\master.dacpac

So, instead of using $(DacpacRootPath)  variable try with the complete path as mentioned and check if the task is working properly.

**Comment by KaineVarley** [comment]
@20shivangi ,

Thank you for your suggestion. The build tools have been installed on an on-premises build server hosting the agent. I can confirm that, with a clean build and install of both the agent and the VS2019 Build Tools, containing the "_Data storage and processing build tools_" workload, **no instance** of the ```master.dacpac``` schema file exists in any location on the server. 

Obviously, I can manually add the ```master.dacpac``` schema file to any location I wish, but this doesn't change the fact that the schema file isn't added during the VS2019 Build Tools installation.

Kaine

**Comment by 20shivangi** [comment]
@KaineVarley 

I tried downloading the VS2019 build tools and was unable to find the master.dacpac file. The same issue has been reported to the Visual Studio team.

Meanwhile, could you check with the path that I mentioned in earlier comment : 
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SQLSchemas\master.dacpac

**Comment by KaineVarley** [comment]
@20shivangi ,

Thanks again for responding. I am pleased that the issue has been observed by the VS team.

With regards to your request to check the path, I'm a little confused since at no point did I mention the path in your initial response:

> The file master.dacpac is not found under path C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools.


In fact, the path in the VS SQL Project file containing the ```$(DacPacRootPath)``` variable:
```
$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SqlSchemas\master.dacpac
```
Resolves correctly to the expected location path:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SqlSchemas\master.dacpac
```

In addition, I have placed a copy of the ```master.dacpac``` in this folder location and confirm that the build is successful.

Perhaps I have misunderstood your request?

Kind regards,


Kaine

**Comment by Ajay-MS** [comment]
@KaineVarley 

Currently `$(DacpacRootPath)`  is resolving to the `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools`

Here @20shivangi  ask is that in VS SQL Project file instead of specifying  `$(DacPacRootPath)` replace its value with `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise` . 

In that case it would be able to figure out the `master.dacpac` file. 

Can you please give a try to this scenario.

**Comment by 20shivangi** [comment]
@KaineVarley

Any update on this ?

**Comment by KaineVarley** [comment]
@Ajay-MS / @20shivangi ,

Please accept my apologies, but I still don't understand. 

Are you suggesting that replacing the ```$(DacPacRootPath)``` with ```C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools``` in the project file will locate the ```master.dacpac``` even though _no instance of the file exists anywhere on the server_? If that is the case, then I'll give it a go.

Kaine

**Comment by Ajay-MS** [comment]
@KaineVarley 

Path that I suggested you ends with `Enterprise` instead of `BuildTools`.

On remote server `master.dacpac` exists at path
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
```

**Comment by KaineVarley** [comment]
@Ajay-MS ,

OK (my mistake), but that still doesn't change the fact that the file **doesn't exist** at any location on the server, including the following (**Enterprise**) location:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\AzureV12\SQLSchemas\
```

Kaine

**Comment by Ajay-MS** [comment]
@KaineVarley 

Actually I found it on my machine so I shared path with you.  As it doesn't exists on your machine  will check with the VSTS team.

**Comment by KaineVarley** [comment]
Thank you @Ajay-MS

**Comment by markingmyname** [comment]
Adding @dhruvanmurthy for awareness

So for VS 2017 it seems they put out the fix as per [15.9.13](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#-visual-studio-2017-version-15913-).

As for VS 2019, the release is expected sometime early July.

Hope this helps.

Thank you.

**Comment by KaineVarley** [comment]
Thanks @markingmyname for the update.

Kaine

**Comment by 20shivangi** [comment]
@markingmyname 

Thanks for the update thereby closing this issue

**Comment by NickFranceschina** [comment]
I am just now running into this.   After researching I learned about the "HintPath" swap solution... then I learned about the update in 15.9.13 that uses the `$(DacPacRootPath)` variable, but that isn't working either because, I think, I have VS 2017 installed on the D:\ drive, and that variable is resolving the c:\ drive where nothing exists.   I'm giving up on all of this and just putting the dacpac files directly into the project for now

**Comment by mohas** [comment]
For people like me that have this problem after removing vs 2017, just unload your project and edit it, find the path mentioned in the error, change ../2017/.. to ../2019/.. , then reload the project

**Comment by rdelgado-incomm** [comment]
Has this problem been solved?  This is still an issue with MS Build Tools 2019: https://stackoverflow.com/questions/58998783/where-does-master-dacpac-come-from-in-vs-2019?noredirect=1#comment104249977_58998783

**Comment by dhruvanmurthy** [comment]
A fix for this issue is being reviewed. We will update this thread once the fix is available for download.

**Comment by dhruvanmurthy** [comment]
A fix for this was released in [16.4.1 version of Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16).

**Comment by andyfisher100** [comment]
I think the actual issue here is that the DACPAC tools aren't included with Visual Studio Build Tools. They are only included with versions of Visual Studio that include the full IDE such as the Enterprise version as far as i know.

Question is, should be be included as part of Visual Studio Build Tools?

**Comment by dhruvanmurthy** [comment]
It should be part of Build Tools now. I just realized that my previous comment was ambiguous and corrected it (link was pointing to build tools though).
Let me know if you are not seeing the master.dacpac installed in latest version of Build Tools.

**Comment by andyfisher100** [comment]
> It should be part of Build Tools now. I just realized that my previous comment was ambiguous and corrected it (link was pointing to build tools though).
> Let me know if you are not seeing the master.dacpac installed in latest version of Build Tools.

You are correct, it looks like it is now part of the VS2019 build tools install. However still not included with the latest VS2017 build tools :(

**Comment by twahl0630** [comment]
so I know this might be closed but I do not get this error in VS 2019 in a local build however I get this error in Azure builds
`<ArtifactReference Include="$(DacPacRootPath)\bin\Debug\master.dacpac">
      <HintPath>$(DacPacRootPath)\bin\Debug\master.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>True</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </ArtifactReference>`

![image](https://user-images.githubusercontent.com/22173646/104775815-9c7da180-573e-11eb-8e18-6584c6a894ff.png)

**Comment by kmkumaran** [comment]
@nadesu , @chshrikh for follow up

**Comment by Andy-INX** [comment]
If anyone is still interested I just came across this in Azure DevOps using VS2019.

We added a MSDB & MASTER DB reference to a SQL Database Project in VS2019.
In a 2nd SQL Database Project we added a MSDB & MASTER DB reference as well as a reference to the 1st project.
Then kept getting "duplicate reference" when building it in Azure DevOps (locally no issues).
Turns out VS added a double-reference to the 1st project - one relative and one absolute! (but not the 2nd - and I would have expected this to happen to the 2nd because it references the 1st?!).
And you get this error when trying to remove (I believe) the absolute path version of the reference.

```xml
  <ItemGroup>
    <ArtifactReference Include="C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac">
      <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </ArtifactReference>
    <ArtifactReference Include="C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac">
      <HintPath>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\IDE\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>False</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>msdb</DatabaseVariableLiteralValue>
    </ArtifactReference>
    <ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac">
      <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\master.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>True</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>master</DatabaseVariableLiteralValue>
    </ArtifactReference>
    <ArtifactReference Include="$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac">
      <HintPath>$(DacPacRootPath)\Extensions\Microsoft\SQLDB\Extensions\SqlServer\130\SqlSchemas\msdb.dacpac</HintPath>
      <SuppressMissingDependenciesErrors>True</SuppressMissingDependenciesErrors>
      <DatabaseVariableLiteralValue>msdb</DatabaseVariableLiteralValue>
    </ArtifactReference>
  </ItemGroup>
```
