### ISSUE TITLE
Universal Packages Download Fails

### ISSUE THREAD

**Issue by rsitrifork** [microsoft/azure-pipelines-tasks#11827]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: DownloadPackage@1

## Environment
Azure Pipelines, Hosted Agent, vs2017-win2016

Code from external git, task denifition via UI as a result

## Issue Description
I added a download artifact task. The task UI allows me to locate the artifact, but in the "View YAML", the names are replaced with IDs, and the task, when running, reports that no feed with that ID exists.

Looking at the yaml documentation for the task, I suspect that the issue is that the feed is project scoped. But the UI offers no way to specify the project.

**Comment by nexaddo** [comment]
I'm experiencing the same error with a newly created feed from the UI

**Comment by panmanphil** [comment]
Also here
`
An unexpected error occurred while trying to download the package. Exit code(19) and error({"@t":"2019-11-20T22:36:40.2603764Z","@m":"The feed with ID 'xxxxxxxxx-b8c7-785d641d3a66' doesn't exist.","@i":"02ddb25b","@l":"Error","SourceContext":"ArtifactTool.Program","UtcTimestamp":"2019-11-20 22:36:40.260Z"})
`

**Comment by pspill** [comment]
This issue is fixed in #11342 and task version 0.160.0, but current hosted pipelines are running 0.158.0.  To address this bug, we need to force an update to the latest version.

**Comment by rsitrifork** [comment]
Sound good that a fix is comming, any timeline? :)

**Comment by Darko-git** [comment]
Any updates?

**Comment by satbai** [comment]
This should be fixed now so closing the issue. Please respond here if you still see this and I'll reopen and  investigate. Thanks!

**Comment by sten-rosendahl** [comment]
I still get the exit code 19 error when the download call is done from the RestoreAndSaveCache task by Microsoft DevLabs.  Project-scoped feed with default permissions.

**Comment by satbai** [comment]
I'm unfamiliar with the RestoreAndSaveCache task by Microsoft DevLabs. It looks like it's an [extension from the Marketplace](https://marketplace.visualstudio.com/items?itemName=1ESLighthouseEng.PipelineArtifactCaching) and lives in [this repo](https://github.com/Microsoft/azure-pipelines-artifact-caching-tasks). Please open an issue in that repo instead. Thanks!
