### ISSUE TITLE
.NetCore: Test - Failed to upload file *.trx

### ISSUE THREAD

**Issue by dwilsonbst** [microsoft/azure-pipelines-tasks#12708]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: .NET Core. Command: test

## Environment
- Server - Azure Pipelines or TFS on-premises? Azure DevOps Services - Azure Pipelines
    
- If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
account/org: bstglobal
team project name: Horizon
Build definition: hz-api-people #20200415.6 (new warning) #20200409.7 (no warning

- Agent - Hosted or Private: Hosted
    
    - If using Hosted agent, provide agent queue name: ubuntu-latest

## Issue Description

.NetCore - test
We are receiving a new warning over the weekend with no new code change. Seems that the hosted agent might be missing a file?

### Task logs

logs attached
[logs_5189.zip](https://github.com/microsoft/azure-pipelines-tasks/files/4487533/logs_5189.zip)

### Error logs

`##[warning]Failed to upload file _fv-az151_2020-04-14_17_38_33.trx to Blob , exception message System.DllNotFoundException: Unable to load shared library 'advapi32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libadvapi32.dll: cannot open shared object file: No such file or directory
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore._executeWithRetry(Func`1 action, Func`1 actionWithRename, Func`1 actionOnSasExpiry, Boolean allowDuplicate, Boolean allowRetryOnNetworkingError, TelemetryTracker telemetryTracker)
   at Microsoft.TeamFoundation.TestClient.PublishTestResults.TestLogStore.UploadInternalAsync(Guid projectId, TestLogScope scope, Int32 buildId, Int32 runId, String logFileSourcePath, Stream stream, String fileName, TestLogType logType, Int32 testResultId, Int32 testSubResultId, Dictionary`2 metaData, TelemetryTracker telTracker, Boolean allowDuplicate, TestLogCompressionType logCompressionType, String originalFileContentType)
Failed to upload run logs to LogStore, Trying to upload to FileService`

**Comment by pf-milan-cihoric** [comment]
We have the same issue on the private agent running on Mac OS after update to 2.166.2.

**Comment by jeromelaban** [comment]
Same issue here, happens when running on hosted macOS. Here's a build sample: https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=14015&view=logs&j=17bb77b0-fb30-5fe7-1844-511c8c531b5b&t=f38f3adc-ca56-5c47-6528-38e22c1972c6&l=17

**Comment by X-Guardian** [comment]
Very similar issue here with the `PublishTestResults` task on the hosted 'ubuntu 16.04' and 'macos-latest' hosted vm images:

- [ubuntu 16.04 image build log](https://dev.azure.com/dsccommunity/DscResource.Common/_build/results?buildId=1500&view=logs&j=7dff0544-c67a-5082-6d8f-af793300b45f&t=78ab6d47-aaf9-5d0f-3b22-229af2adc075)
- [macos-latest image build log](https://dev.azure.com/dsccommunity/DscResource.Common/_build/results?buildId=1500&view=logs&j=4a586ee7-88e1-5b4c-8df6-320f736717f1&t=5b73ad67-5eaf-5726-fa09-7ab231bbfd5b)

**Comment by bugraderre** [comment]
The very same failure for us

**Comment by bishal-pdMSFT** [comment]
@phanikmmsft can you please look at this - it is related to test command in .Net Core task.

**Comment by phanikmmsft** [comment]
I believe this was already fixed.
@shailesh-sk  please confirm and close

**Comment by shailesh-sk** [comment]
Yes this issue is already mitigated last week. Please let us know if you are still seeing the issue again.

**Comment by issacnitin** [comment]
@dwilsonbst Closing this issue as we couldn't receive a response from you. Please feel free to re-open if the issue persists

**Comment by deepanshuverma** [comment]
The issue is still there for us in our pipelines, could you please share if anything we need to change on our side to get the fix.
