### ISSUE TITLE
MavenAuthenticate@0 task is throwing error "cp: dest file already exists: /root/.m2/_settings.xml"

### ISSUE THREAD

**Issue by sheikahamedali** [microsoft/azure-pipelines-tasks#13569]
## Note  
The MavenAuthenticate@0 task is throwing  "cp: dest file already exists: /root/.m2/_settings.xml" while running the pipeline task on the Linux OS agent. The same task use to work until today morning without any errors. 

Here is the complete error description from the task.

Starting: Maven Authenticate
==============================================================================
Task         : Maven Authenticate
Description  : Provides credentials for Azure Artifacts feeds and external maven repositories
Version      : 0.175.1
Author       : Microsoft Corporation
Help         : https://go.microsoft.com/fwlink/?linkid=2099968
==============================================================================
cp: dest file already exists: /root/.m2/_settings.xml

##[error]Failed cp: cp: dest file already exists: /root/.m2/_settings.xml

Finishing: Maven Authenticate

For a list:  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

If you have an issue or request for the Azure Pipelines service, use developer community instead:  

https://developercommunity.visualstudio.com/spaces/21/index.html )

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: MavenAuthenticate@0

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: Ingramcontent

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: lvick8sd-dind-ado-build-agent-2

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

The MavenAuthenticate@0 task is throwing  "cp: dest file already exists: /root/.m2/_settings.xml" while running the pipeline task on the Linux OS agent. The same task use to work until today morning without any errors. 

### Task logs

Here is the complete error description from the task.

Starting: Maven Authenticate
==============================================================================
Task         : Maven Authenticate
Description  : Provides credentials for Azure Artifacts feeds and external maven repositories
Version      : 0.175.1
Author       : Microsoft Corporation
Help         : https://go.microsoft.com/fwlink/?linkid=2099968
==============================================================================
cp: dest file already exists: /root/.m2/_settings.xml

##[error]Failed cp: cp: dest file already exists: /root/.m2/_settings.xml

Finishing: Maven Authenticate
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

Here is the complete error description from the task.

Starting: Maven Authenticate
==============================================================================
Task         : Maven Authenticate
Description  : Provides credentials for Azure Artifacts feeds and external maven repositories
Version      : 0.175.1
Author       : Microsoft Corporation
Help         : https://go.microsoft.com/fwlink/?linkid=2099968
==============================================================================
cp: dest file already exists: /root/.m2/_settings.xml

##[error]Failed cp: cp: dest file already exists: /root/.m2/_settings.xml

Finishing: Maven Authenticate

**Comment by omokoh** [comment]
Hey,

We just sent a fix for this issue. Is it currently resolved?

**Comment by sheikahamedali** [comment]
Thank you for the fix. The mavenAuthenticate task seems to be working fine.

**Comment by mak-dt-rtl** [comment]
Has this been deployed to Production?

**Comment by anatolybolshakov** [comment]
Hi @sheikahamedali thanks, I'm closing it since it's resolved

**Comment by Cadacious** [comment]
Was this fix pushed to production? We are on version 0.177.1 of this task and seeing this exact issue intermittently in our pipeline.

**Comment by Cadacious** [comment]
@anatolybolshakov following up on my previous comment on this.

We were able to track this down to a race condition where multiple pipelines were running the maven authenticate task at the same time. Because this file is written to the `%USERPROFILE%\.m2\settings.xml` location (on Windows) this task can only be in active execution by one agent on a server a time. We host 5 agents per server in our organization.

Is it possible to write this file to the agent directory instead of a global location like the user profile? This would allow the settings file to be contained to the agent that is running it.

It may also be possible to add in a delay and a retry, with a failure occurring if the error happens again. It won't completely negate the issue, but it can avoid needing to jiggle the handle on the pipeline when it may succeed on re-run.

**Comment by BalintKorcsmar629** [comment]
@Cadacious i can see the pull request on the above link is still open. Is there an estimated time of availability for this?

For me this also happens intermittently when more than 1 job is running parallel, because the settings.xml is in a shared linux folder.

I am getting the same error:
##[error]Failed cp: cp: dest file already exists: $HOME/.m2/_settings.xml

On some occasions the settings.xml was completely deleted after the pipeline run.

**Comment by rcomanne** [comment]
Please approve the PR of @Cadacious as the race condition is still happening from time to time, meaning we cannot run multiple agents on one host without issues.

**Comment by BalintKorcsmar629** [comment]
The issue is closed but it is not merged back to master, the pull request related to this issue is still open. So closing this issue means the Azure Pipelines team is aware of the issue but do not wish to fix it?

**Comment by rcomanne** [comment]
I guess the comment of omokoh made them think the issue was resolved?
However, we are still getting these errors, so they are not...

**Comment by BalintKorcsmar629** [comment]
@anatolybolshakov please reopen this issue because it is not resolved. Please merge the pull request above so we can use Maven Authenticate task.

**Comment by Cadacious** [comment]
@BalintKorcsmar629 i jumped the gun on submitting the PR and did not have permission from my employer to sign the document as this was discovered and developed in the course of my work. Someone else may need to submit the PR while I work through the red-tape.

However, upon further review of this after submitting the PR I was unsure if changing this file location would actually change the behavior of Maven to consume this file from the new location [$(Agent.TempDirectory)] instead of the default location.

@anatolybolshakov per your comment on the PR, does this need to be a customizable value? What scenarios would a user be bringing their own settings.xml when using the Maven Authenticate task?

**Comment by anatolybolshakov** [comment]
@Cadacious could it make sense to add some switch input to allow turn on/off this behavior instead? The main concern here from our side is just to avoid unexpected behavior changes for existing logic, since some users can rely on this.

**Comment by Cadacious** [comment]
@anatolybolshakov I can definitely add that in to the PR. I am going through the approval process within my company to get permission to move forward. 

I would have to see how other tasks implemented this kind of configuration option, but I would think a checkbox that is defaulted to unchecked that says "Use agent temp directory for settings.xml" or something along those lines would suffice here. That way the new behavior is opt-in and doesn't cause a breaking change.

**Comment by Cadacious** [comment]
@anatolybolshakov I can definitely add an input field to toggle this behavior. Would adding a group to contain this setting be needed or can it be visible by default (but not selected by default) with the currently available settings?

I would also use a MarkdownHelp value of "Utilizes $(Agent.TempDirectory) to avoid race condition when running multiple Maven Authenticate tasks on agents running as the same user on the same server" to give an indication to users why this may be needed.

**Comment by anatolybolshakov** [comment]
@Cadacious I think it could make sense to put it to advanced group also - since useAgentTempDir input is already in this group.

**Comment by joshguptill** [comment]
Bump - is anyone still actively working on this one?

**Comment by steve-sap** [comment]
Any chance of someone picking this up?
