### ISSUE TITLE
AzureResourceGroupDeploymentV2 - Escaping [ results in [[ after deployment.

### ISSUE THREAD

**Issue by Ceespino** [microsoft/azure-pipelines-tasks#13593]
## Note  
Deploying an ARM template using this extension gives a different result than deploying the ARM template using Powershell or [Azure Portal](https://ms.portal.azure.com/#create/Microsoft.Template). 

Using this task, when I am deploying a parameter of type **string** with the following value **[[someValue]**,  the value is deployed as **[[someValue]**, however, if I use the same ARM template in Powershell or Azure Portal, the result is deployed as **[someValue]** (the ARM escape character is honored).

I think there's an issue in the extension when deploying values that are escaping the [ character for ARM expressions.

## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: AzureResourceGroupDeploymentV2 

list here (V# not needed):  
https://github.com/microsoft/azure-pipelines-tasks/blob/master/Tasks/AzureResourceGroupDeploymentV2/README.md

## Environment
- Server - Azure Pipelines
    
Account: **ceespino**
Project: **ceespino-ms**
Release definition name: **Release to ceespino-CICD-Target**

## Issue Description

Deploying an ARM template using this extension gives a different result than deploying the ARM template using Powershell or [Azure Portal](https://ms.portal.azure.com/#create/Microsoft.Template). 

Using this task, when I am deploying a parameter of type **string** with the following value **[[someValue]**,  the value is deployed as **[[someValue]**, however, if I use the same ARM template in Powershell or Azure Portal, the result is deployed as **[someValue]** (the ARM escape character is honored).

I think there's an issue in the extension when deploying values that are escaping the [ character for ARM expressions.

### Task logs

[Enable debug logging and please provide the zip file containing all the logs for a speedy resolution]

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

There's no error message since deployment succeeds, the problem is that the template deployment gives a different result than if deployed through PS or Azure portal.

Attached template to repro the problem.

[ArmTemplate_BugRepro.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5264820/ArmTemplate_BugRepro.txt)

**Comment by tejasd1990** [comment]
Hi @Ceespino , I was not able to repro this issue. I deployed the same template you attached, through the `AzureResourceGroupDeploymentV2` task, and a trigger parameter with value `[someValue]` was created. Can you check once again that the values in your template are correct?

**Comment by Ceespino** [comment]
@tejasd1990 
I just deployed the ARM template again using the task and still getting the parameter value with `[[someValue]`.

![image](https://user-images.githubusercontent.com/40403944/94461219-b33bc080-016e-11eb-9d82-63b484dbd158.png)

Could you please walk me through how are you trying to repro the problem?
I basically have the task pointing to the ARM template file in a repo, then just deploying it to a data factory.

**Comment by tejasd1990** [comment]
Hi @Ceespino ,
I deployed the template containing
```
"ScheduleTrigger_properties_waitPipeline2_parameters_pipelineParam": {
    "defaultValue": "[[someValue]",
    "type": "String"
},
```

After deployment, on the data factory resource,
`Overview` -> `Author & Monitor`. 
This navigates to the data factory page. Inside the data factory,
`Author` -> `Factory Resources` -> `Pipelines` -> Select the pipeline -> `Triggers` -> Select the trigger -> `Parameters` -> `pipelineParam`

The value of the parameter is `[someValue]`

**Comment by Ceespino** [comment]
@tejasd1990 
Is it possible that you are overriding the parameter during deployment in the ADO task? I still can deploy the attached ARM template and get the double **[[**. I can repro this consistently with the ADO task. It works fine with PS or Azure Portal.

**Comment by tejasd1990** [comment]
@Ceespino , no the parameters are not getting overridden. Can you share the complete debug logs of the task(even if they are succeeding)?

**Comment by tejasd1990** [comment]
As discussed offline, this is expected, and explained [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions#escape-characters). The `defaultValue` of a parameter in the template file will get escaped, but parameter values passed through command line, or through parameters file will not. 
Closing this issue.

**Comment by n1cho1as** [comment]
Guys this is still an issue. I'm the one who first reported it and have encountered it by embedding a JSON map within a JSON Object parameter on the trigger. To reproduce the issue simply configure a trigger with a JSON object parameter and then publish it in your GIT enabled ADF instance. You'll immediately see that the JSON template value in the **adf_publish** branch will now contain an extra [ bracket that then causes a failure when the value is actually used as a map in a copy activity. 

[Support.Example.json.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5499799/Support.Example.json.zip)

**Comment by n1cho1as** [comment]
I also looked at your link and it does not address this issue. The data becomes corrupted by the publish task which then causes a copy activity to fail as the extra [[ is not removed from the execution payload when the trigger fires.

If you were to edit the trigger manually with the raw value and publish it using a non-git enabled ADF instance it does not add the extra square bracket, this happens with the transition to the **adf_publish** branch.
