### ISSUE TITLE
Gradle build in Azure Devops Failure

### ISSUE THREAD

**Issue by aafnan10** [microsoft/azure-pipelines-tasks#13931]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Gradle  

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - Azure Pipelines
   
- Agent - Hosted or Private: 
    
    - Hosted

## Issue Description

I'm using Gradle task in Azure DevOps build pipeline. Since today I'm facing failures in Gradle build. Usually, build task takes almost 5 minutes. But currently, it is taking more than 20 minutes and still fails.

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs

```
Starting: Run Build PROJ
==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.178.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
==============================================================================
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
##[warning]Resource file has already set to: /home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-tasks-codecoverage-tools/module.json
SYSTEMVSSCONNECTION exists true
/home/vsts/work/1/s/proj/gradlew -PbuildEnv=alpha -PsetUp=cloud build
Downloading https://services.gradle.org/distributions/gradle-5.4.1-bin.zip
...................................................................................

Welcome to Gradle 5.4.1!

Here are the highlights of this release:
 - Run builds with JDK12
 - New API for Incremental Tasks
 - Updates to native projects, including Swift 5 support

For more details see https://docs.gradle.org/5.4.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':proj'.
> Could not resolve all dependencies for configuration ':proj:classpath'.
   > Could not determine artifacts for org.springframework.boot:spring-boot-gradle-plugin:2.2.0.RELEASE: Skipped due to earlier error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8m 4s
Error: The process '/home/vsts/work/1/s/proj/gradlew' failed with exit code 1
    at ExecState._setResult (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:816:25)
    at ExecState.CheckComplete (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:799:18)
    at ChildProcess.<anonymous> (/home/vsts/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.178.0/node_modules/azure-pipelines-task-lib/toolrunner.js:721:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
No test result files matching /home/vsts/work/1/s/**/TEST-*.xml were found, so publishing JUnit test results is being skipped.
##[error]Error: The process '/home/vsts/work/1/s/proj/gradlew' failed with exit code 1
Finishing: Run Build PROJ
```

**Comment by EzzhevNikita** [comment]
@aafnan10 Could you please provide some additional logs:
* Run pipeline with enabled diagnostics ([Here](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs) the info how to enable this option)
* Pass '--debug' option to the [Options ](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/gradle?view=azure-devops#arguments) input in Gradle task

And share the resulting log here

**Comment by EzzhevNikita** [comment]
Hey @aafnan10, is still actual issue for you?

**Comment by aafnan10** [comment]
Hi @EzzhevNikita, This issue is now resolved. It is not occurring now.

**Comment by EzzhevNikita** [comment]
As the issue is resolved for you now, I'm closing this ticket. Feel free to reopen it at any time if the problem will appear once again.

**Comment by declankilker** [comment]
> Hi @EzzhevNikita, This issue is now resolved. It is not occurring now.

@aafnan10 - Do you know how this issue was resolved? We're still seeing the same warning on our Azure build pipeline.

**Comment by aafnan10** [comment]
Hi @declankilker, This issue was related to Gradle task failure. The Gradle task in Azure DevOps was unable to download certain packages.  It may be due to some incident that happened in Azure US and it was fixed later. But the warnings are still occurring. I have opened another [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/13916) on the warnings.  It is not fixed yet.

**Comment by declankilker** [comment]
> Hi @declankilker, This issue was related to Gradle task failure. The Gradle task in Azure DevOps was unable to download certain packages. It may be due to some incident that happened in Azure US and it was fixed later. But the warnings are still occurring. I have opened another [issue](https://github.com/microsoft/azure-pipelines-tasks/issues/13916) on the warnings. It is not fixed yet.

Great, thanks @aafnan10

**Comment by richanshah** [comment]
@declankilker, we cannot resolve this issue can anyone suggest the steps?

**Comment by babishan09** [comment]
@aafnan10 We are also facing the same issue, can you please share us the steps to resolve this issue?

**Comment by srinivas508** [comment]
I'm using Gradle task in Azure DevOps build pipeline for android application. Since today I'm facing failures in Gradle build. I'm getting this error continously

- changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 3m 5s
5 actionable tasks: 5 executed
Error: The process '/Users/runner/work/1/s/android/gradlew' failed with exit code 1
    at ExecState._setResult (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.211.0/node_modules/azure-pipelines-task-lib/toolrunner.js:942:25)
    at ExecState.CheckComplete (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.211.0/node_modules/azure-pipelines-task-lib/toolrunner.js:925:18)
    at ChildProcess.<anonymous> (/Users/runner/work/_tasks/Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4/2.211.0/node_modules/azure-pipelines-task-lib/toolrunner.js:838:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:527:28)
    at Pipe.<anonymous> (node:net:709:12)
##[error]Error: The process '/Users/runner/work/1/s/android/gradlew' failed with exit code 1
