### ISSUE TITLE
"VsTest task failed" with no additional info or errors

### ISSUE THREAD

**Issue by jamers99** [microsoft/azure-pipelines-tasks#14314]
## Required Information
*Type*: Bug
**Task**: Visual Studio Test

## Environment
Private Agent on Windows 10, version 2.181.0

## Issue Description
Our Visual Studio Test task is failing in or YAML build on only one of our agents *sometimes*. 

![image](https://user-images.githubusercontent.com/20806279/106279068-da33fd00-6209-11eb-831c-46a4db0fd7e3.png)

We started experiencing the issue around the 27th. It was happening about 1 in 5-7 times. On the 28th I deleted the work folders and the _temp and _tasks cache folders. It then worked for a while (15ish hour period with around 20 builds) with no issues. But then on the 29th it started happening again (2 out of the last 3)

### Task logs
```
Starting: Run parallel tests
==============================================================================
Task         : Visual Studio Test
Description  : Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner. Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run. Tests can be distributed on multiple agents using this task (version 2).
Version      : 2.170.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/vstest
==============================================================================
SystemVssConnection exists true
SystemVssConnection exists true
Running tests using vstest.console.exe runner.
======================================================
Test selector : Test assemblies
Test filter criteria : null
Search folder : C:\A\Default\w\2181\s\Output\Debug
Action when minimum tests threshold not met : fail
Minimum tests expected to be run: 10
VisualStudio version selected for test execution : latest
Attempting to find vstest.console from a visual studio installation with version [16.0,17.0).
Run settings file : C:\A\Default\w\2181\s\TestRunConfigurationInParallel.runsettings
Run in parallel : false
Run in isolation : false
Path to custom adapters : null
Other console options : --blame
Code coverage enabled : false
Diagnostics enabled : false
SystemVssConnection exists true
Run the tests locally using vstest.console.exe
========================================================
Source filter: **\*vision*.dll,**\*expenses*.dll,**\*financial*.dll,**\*general*.dll,**\*inventory*.dll,**\*labor*.dll,**\*sales*.dll,!**\*general_*.dll,!**\General.Demo.dll,!**\General.Reporting.Communications.dll,**\model.dll,!**\Common\model.dll,!publish\**,!**\ref\**,!**\win-x86\**,!**\*microsoft*,!**\testhost*
======================================================
##[error]VsTest task failed.
Finishing: Run parallel tests
```
I am enabling debug logs and will update when I get another failure with that enabled.

### Error logs
`##[error]VsTest task failed.`

**Comment by jamers99** [comment]
@damccorm we're getting this very frequently now. Here are the debug logs for the step: 
[vstest.txt](https://github.com/microsoft/azure-pipelines-tasks/files/5911308/vstest.txt)

**Comment by jamers99** [comment]
We again deleted the **_temp**, **_tasks**, and additionally this time the **_tools** directories and it worked for about a week, but the issue came up again. I'm uninstalling and deleting the agent and reinstalling to see if that makes any difference.

**Comment by ankit-arora12** [comment]
It seems like an issue with the environment. 

- Please check agent diagnostic logs (which can be enabled from the UI) to see if the azure pipeline agent is giving some error.
- Can you please check if publish test results task is running fine?
- Also, please check if it's running on the hosted agents?

**Comment by jamers99** [comment]
We haven't gotten this in a long time, so it seems the uninstall and reinstall of the agent fixed the issue.

**Comment by ankit-arora12** [comment]
I guess there was some miscommunication regarding my asks. I meant to check 'Agent Diagnostics logs'. The tagged logs are for vstest task logs. And in the third point, I meant for you to validate if the issue goes away if you switch to hosted agents.

But good to know that the issue is now fixed.

**Comment by jamers99** [comment]
Well, it happened again today. Same machine. Same issue. I'll uninstall and reinstall again so it doesn't happen, but it seems like there is still an issue here...

**Comment by jamers99** [comment]
@ankit-arora12, can this be reopened?

**Comment by ankit-arora12** [comment]
Can you please try if the issue goes away when you switch to the hosted agent?

**Comment by jamers99** [comment]
We cannot run this build on a hosted agent

**Comment by ankit-arora12** [comment]
Since these are private agents, we need some help from you to debug the issue better. Can you please add console.log around a js file mentioned below and rerun the pipeline and share the debug logs with us?

Lines where these logs need to be added:
1. https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/VsTestV2/nondistributedtest.ts#L92
https://github.com/microsoft/azure-pipelines-tasks/blob/acc64cc7292c98597908325e53af9f898a896189/Tasks/VsTestV2/nondistributedtest.ts#L95

These lines are part of file `nondistributedtest.js` which can be found in the agent directory of vstest task.
