### ISSUE TITLE
Download Jenkins artifacts fails with ExtractionFailed Error: Unsupported file type "undefined"

### ISSUE THREAD

**Issue by sarukk** [microsoft/azure-pipelines-tasks#14320]
## Required Information

Entering this information will route you directly to the right team and expedite traction.

**Question, Bug, or Feature?**  
Bug

**Enter Task Name**: Jenkins download artifacts

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    Azure Pipelines: PG-CT/DIAC/ReleaseAndCiScripts Trigger

- Agent - Hosted or Private: 
     Private: Windows Server 2012 R2

## Issue Description

We have moved our pipelines from one organization to another. after this move, the Jenkins download artifact task started to fail, when it is trying to extract the downloaded artifact:

`2021-02-01T10:57:30.3729956Z ##[section]Starting: Download artifacts produced by DIAC/ReleaseAndCiScripts
2021-02-01T10:57:30.3866217Z ==============================================================================
2021-02-01T10:57:30.3866604Z Task         : Jenkins download artifacts
2021-02-01T10:57:30.3866914Z Description  : Download artifacts produced by a Jenkins job
2021-02-01T10:57:30.3867198Z Version      : 1.175.0
2021-02-01T10:57:30.3867423Z Author       : Microsoft
2021-02-01T10:57:30.3867876Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/jenkins-download-artifacts
2021-02-01T10:57:30.3868293Z ==============================================================================
2021-02-01T10:57:32.3462228Z Downloading content from Jenkins server:https://XXX/jenkins//job/DIAC/job/ReleaseAndCiScripts//api/json with strict SSL:false
2021-02-01T10:57:32.3683842Z Download artifacts from last successful build of DIAC/ReleaseAndCiScripts
2021-02-01T10:57:32.9371670Z Found job type org.jenkinsci.plugins.workflow.job.WorkflowJob
2021-02-01T10:57:32.9406506Z Downloading content from Jenkins server:https://XXX/jenkins//job/DIAC/job/ReleaseAndCiScripts//api/json?tree=lastSuccessfulBuild[id,displayname] with strict SSL:false
2021-02-01T10:57:33.4743316Z Found Jenkins job details jobName:DIAC/ReleaseAndCiScripts, jobType:org.jenkinsci.plugins.workflow.job.WorkflowJob, buildId:274, branchName:undefined
2021-02-01T10:57:34.0748456Z Downloading artifacts from: https://XXX/jenkins///job/DIAC/job/ReleaseAndCiScripts//274/artifact/*zip*/
2021-02-01T10:57:34.7577721Z Downloading  to C:\agent\_work\1\s\jenkinsArtifacts\archive.zip
2021-02-01T10:57:34.7918752Z Downloaded  to C:\agent\_work\1\s\jenkinsArtifacts\archive.zip
2021-02-01T10:57:35.0867427Z Total Files: 1, Processed: 1, Skipped: 0, Failed: 0, Download time: 1.01 secs, Download size: 0Bytes
2021-02-01T10:57:35.1542149Z ##[warning]Can\'t find loc string for key: ExtractionFailed
2021-02-01T10:57:35.1558149Z ##[error]ExtractionFailed Error: Unsupported file type "undefined"
    at DecompressZip.extractFile (C:\agent\_work\_tasks\JenkinsDownloadArtifacts_86c37a92-59a7-444b-93c7-220fcf91e29c\1.175.0\node_modules\decompress-zip\lib\decompress-zip.js:309:11)
    at C:\agent\_work\_tasks\JenkinsDownloadArtifacts_86c37a92-59a7-444b-93c7-220fcf91e29c\1.175.0\node_modules\decompress-zip\lib\decompress-zip.js:242:28
    at Array.forEach (native)
    at DecompressZip.extractFiles (C:\agent\_work\_tasks\JenkinsDownloadArtifacts_86c37a92-59a7-444b-93c7-220fcf91e29c\1.175.0\node_modules\decompress-zip\lib\decompress-zip.js:241:11)
    at C:\agent\_work\_tasks\JenkinsDownloadArtifacts_86c37a92-59a7-444b-93c7-220fcf91e29c\1.175.0\node_modules\decompress-zip\lib\decompress-zip.js:121:21
    at _fulfilled (C:\agent\_work\_tasks\JenkinsDownloadArtifacts_86c37a92-59a7-444b-93c7-220fcf91e29c\1.175.0\node_modules\q\q.js:854:54)
`

### Task logs

[debugLogs.zip](https://github.com/microsoft/azure-pipelines-tasks/files/5903653/debugLogs.zip)

### Error logs

2021-02-01T10:57:35.1542149Z ##[warning]Can\'t find loc string for key: ExtractionFailed
2021-02-01T10:57:35.1558149Z ##[error]ExtractionFailed Error: Unsupported file type "undefined"
    at DecompressZip.extractFile (C:\agent\_work\_tasks\JenkinsDownloadArtifacts_86c37a92-59a7-444b-93c7-220fcf91e29c\1.175.0\node_modules\decompress-zip\lib\decompress-zip.js:309:11)

**Comment by john-forrest** [comment]
We have noticed something very similar in the last few days. We had another issue that was preventing the Azure Devops job from being triggered. Last job that worked was the 25th Dec. Fixed the trigger issue last Friday (29th Jan) and now see this.
In the meantime we have updated Jenkins from LTS 2.263.1 to 2.263.3. There are some suggestions of changes in the zip format in the latter, even though at least some of the fixes are reported as regression issues for 2.263.2. I am wondering if the format has changed over this time and Azure Devops is having problems coping.

**Comment by john-forrest** [comment]
I have downgraded our Jenkins instance from 2.263.3 to 2.263.1 and the link to Azure Devops has now started working again.
I have also compared the behaviour of using the "(all files in zip)" under artifacts - the code on Azure Devops appears to be using the equivalent of this. The behaviour of this command has indeed changed - based on the Jenkins released notes, it seems deliberately so. Let's assume that the file we were trying to send is called foo.zip. The old (2.263.1) behaviour creates a file called archive.zip which in turn contains foo.zip at its root level. The new (2.263.1) behaviour still creates file archive.zip but its contents are slightly different: inside the zip there is a top-level directory archive and foo.zip is inside that directory. 
My suggestion is that the Adevops code is updated to handle both scenarios - either automatically or there being an option.

**Comment by john-forrest** [comment]
**Note**: I may have got the above analysis the wrong way around (it might be the 2.263.1 version that has got the extra directory) but definitely downgrading to 2.263.1 seems to fix the problem. This sounds related to the following Jenkins issue [JENKINS-64621](https://issues.jenkins.io/browse/JENKINS-64621), although that claims to have been fixed for 2.263.3.

**Comment by john-forrest** [comment]
I've now tried  Jenkins 2.263.4. The change of behaviour with archive.zip I noticed seems to have been fixed (the file structure of the zip is the same as 2.263.1) but I still see the problem reported. Suggestion then is that the real issue is something different. Currently my only solution is to stick to Jenkins 2.263.1, which continues to work. That is not a long term solution.

**Comment by eleasysoft** [comment]
I have the same issue with Azure DevOps on hosted Nodes with Jenkins 2.281
The same environment as previsouly worked for a few weeks.
I assume that changes made in Jenkins 2.276 may habe brocken the Azure task.

**Comment by vagpap** [comment]
Reporting the same issue using Jenkins 2.283 currently, but have also faced it with 2.282.

Hosted agent v2.179.0 @ Windows Server 2019 Standard

**Comment by ngcdev** [comment]
I'm too experiencing this issue and it seems related to a change in Jenkins output. Although I see the same folder structure, the file must be different in some way that Azure cannot identify. I upgraded to Jenkins 2.277.1 and the issue still remains. So, as mentioned by others, I'm sticking with 2.263.1
Based on the error logs, it seems like it might be an issue with the Node package used for unzipping.

**Comment by samvdd-247** [comment]
Facing the same problems when using ubuntu 16.04 and Jenkins 2.277.1

**Comment by DaniilShmelev** [comment]
@narula0781 hi, do you have any progress on this issue?
We found that it is reproducible on the latest jenkins server

**Comment by harshiniks** [comment]
I tested this with Jenkins server 2.6 and later upgraded it to 2.7 and could reproduce the issue. After debugging, issue seems to be with Jenkins server compression, artifacts folder that gets downloaded from Jenkins has all the files but the type of the file is missing in its metadata which is resulting in this failure.

Example file detail from debugging:
 FileDetails {
    _offset: 418,
    _maxSize: 22,
    parent: 'archive',
    filename: 'test.txt',
    path: 'archive\\test.txt',
    **type: undefined,**
    mode: 420,
    compressionMethod: 8,
    modified: 2021-04-26T07:19:56.000Z,
    crc32: 3092708862,
    compressedSize: 22,
    uncompressedSize: 20,
    comment: '',
    flags:
     { encrypted: false,
       compressionFlag1: false,
       compressionFlag2: false,
       useDataDescriptor: true,
       enhancedDeflating: false,
       compressedPatched: false,
       strongEncryption: false,
       utf8: true,
       encryptedCD: false } }

Due to this unzip of the folder is failing. We need to raise a bug with Jenkins to look into this as there is not much we can do at task end.

**Comment by harshiniks** [comment]
Workaround is to downgrade Jenkins.
We will reopen this if we hear back from Jenkins end.

**Comment by john-forrest** [comment]
@harshiniks could you post the reference to the Jenkins ticket you have I assume by now raised?

**Comment by mstfn** [comment]
I have located the bug.
The OSS dependency `"decompress-zip": "0.3.0"` defaults to `'undefined'` file type for directory entries in zip files if the zip file is labeled as created on UNIX.
I made a small test program to extract the Jenkins generated zip in the same way as the task, and this bug causes the extraction failure with the same error message.

Solution is to update to `"decompress-zip": "0.3.3"`

I have not tested this in place, and the history for `DownloadBuildArtifactsV0` implies this might need other dependencies to be updated.

**Comment by john-forrest** [comment]
@harshiniks will you take the change suggested by @mstfn ?

**Comment by anatolybolshakov** [comment]
HI @john-forrest let us take a look

**Comment by rafstef** [comment]
We have the same problem, the azure unzip return: ExtractionFailed Error: Unsupported file type "undefined"

Are there workaround that not ask the jenkins downgrade?

**Comment by john-forrest** [comment]
I see this links to #15007

**Comment by harshiniks** [comment]
This is resolved now with latest version of task 1.90
