### ISSUE TITLE
Exit code -1073741819 - Can't download secure file self-hosted agent. 

### ISSUE THREAD

**Issue by adurangalvis** [microsoft/azure-pipelines-tasks#16337]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Pre-job: DownloadSecureFile, DownloadSecureFile@1

list here (V# not needed):  
https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks

## Environment
- Server - Azure Pipelines or TFS on-premises?
    
    - If using TFS on-premises, provide the version: Azure Pipelines with self hosted agent. Agent v2.202.1
    
    - If using Azure Pipelines, provide the account name, team project name, build definition name/build number: 
      DSSINC4, TRM Plus Web, code_test/code_sign_test, #20220518.1 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
       Windows Server 2019, Agent v2.202.1
## Issue Description
When trying to download secure file with hosted agent we get an error with node, the tool is in the agent folder and we have tried to remove and install agent again and same thing happening. I tried the job on MS Hosted agent and is able to download the file just fine, but we need this job on our own hosted agent. 

### Task logs
Logs here:
[logs_67237.zip](https://github.com/microsoft/azure-pipelines-tasks/files/8717160/logs_67237.zip)

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

### Error logs
```
[Include task name(s), screenshots and any other relevant details]
2022-05-18T14:12:31.1191852Z ##[debug]Evaluating condition for step: 'DownloadSecureFile'
2022-05-18T14:12:31.1277733Z ##[debug]Evaluating: SucceededNode()
2022-05-18T14:12:31.1289018Z ##[debug]Evaluating SucceededNode:
2022-05-18T14:12:31.1361273Z ##[debug]=> True
2022-05-18T14:12:31.1377151Z ##[debug]Result: True
2022-05-18T14:12:31.1458834Z ##[section]Starting: DownloadSecureFile
2022-05-18T14:12:31.2214245Z ==============================================================================
2022-05-18T14:12:31.2215093Z Task         : Download secure file
2022-05-18T14:12:31.2216094Z Description  : Download a secure file to the agent machine
2022-05-18T14:12:31.2216496Z Version      : 1.200.0
2022-05-18T14:12:31.2217042Z Author       : Microsoft Corporation
2022-05-18T14:12:31.2217867Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/download-secure-file
2022-05-18T14:12:31.2218857Z ==============================================================================
2022-05-18T14:12:31.2764838Z ##[debug]Using node path: C:\agent\externals\node10\bin\node.exe
2022-05-18T14:12:33.3892165Z ##[error]Exit code -1073741819 returned from process: file name 'C:\agent\externals\node10\bin\node.exe', arguments '"C:\agent\_work\_tasks\DownloadSecureFile_2a6ca863-f2ce-4f4d-8bcb-15e64608ec4b\1.200.0\predownloadsecurefile.js"'.
2022-05-18T14:12:33.3912859Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code -1073741819 returned from process: file name 'C:\agent\externals\node10\bin\node.exe', arguments '"C:\agent\_work\_tasks\DownloadSecureFile_2a6ca863-f2ce-4f4d-8bcb-15e64608ec4b\1.200.0\predownloadsecurefile.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2022-05-18T14:12:33.3922954Z ##[section]Finishing: DownloadSecureFile
```

**Comment by DmitriiBobreshev** [comment]
Hi @adurangalvis, it looks like you have an 0xC0000005 error, according to the[ MS Codes table](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-) -
this is an `ERROR_ACCESS_DENIED` error it could show up when the NodeJS process doesn't have permission to work with the 
"_tmp" agent's folder (e.g.: C:\agent\_work\_temp in your case).

Could you check if the user under which the agent is running has all the necessary permission to work with the agent folder? 

Also, I have implemented a fix to our task-lib to make the error message more user-friendly: 
- microsoft/azure-pipelines-task-lib/pull/845

**Comment by adurangalvis** [comment]
@DmitriiBobreshev  thank  you for looking into this. The service account that is running the agent is an admin, but I went ahead and provided explicit permissions to the account to have full access control to root path of agent. I restarted the agent and tried again and unfortunately I get the same error.
![agent_permissions](https://user-images.githubusercontent.com/72407308/173668708-463022c6-3a0f-4700-b59d-5a63f2a5f2a6.png)

**Comment by adurangalvis** [comment]
I created a new agent and this time made sure I created it with the service account I want it from the beginning. I am still getting the same error, also verified the account has full control on root folder. I also looked at the logs to see the error it is stating in the powershell output put all I see is error it can't find a Java installation. 
![agent_permissions](https://user-images.githubusercontent.com/72407308/173903349-366c26b7-e6c0-457c-a415-9da057f3a149.png)
`[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + 
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry32', key name 'Software\JavaSoft\JRE'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + 
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry64', key name 'Software\JavaSoft\Java Runtime Environment'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + _x64
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry64', key name 'Software\JavaSoft\JRE'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + _x64
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry64', key name 'Software\AdoptOpenJDK\JRE'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + _x64
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry64', key name 'Software\AdoptOpenJDK\JRE'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + _x64
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry64', key name 'Software\Eclipse Foundation\JRE'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + _x64
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Checking: hive 'LocalMachine', view 'Registry64', key name 'Software\Semeru\JRE'
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Key not found.
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: An error occured while trying to sort subkeys for capability as versions:  java_ + <version> + _x64
[2022-06-15 13:59:36Z INFO PowerShellCapabilitiesProvider] STDOUT: Cannot index into a null array.`

**Comment by adurangalvis** [comment]
I also ran a powershellscript to check permissions of the root agent folder in the pipeline.

![powershell_check](https://user-images.githubusercontent.com/72407308/173919458-e4493566-77a2-481b-b5ff-5316b8caedf2.png)

**Comment by adurangalvis** [comment]
I logged in as the service account and went to the agent node10 path and tried to run the .js file and didn't get any permissions issues just its missing inputs as expected. 
![node_js_call](https://user-images.githubusercontent.com/72407308/173923682-6e491a36-8a74-4a21-9439-e2bf654cae64.png)

**Comment by DmitriiBobreshev** [comment]
Hello @adurangalvis, thank you for the detailed answer and sorry for the really late response.
As I can see, you have all permissions to _tml folder and probably not with that.
Could you please provide some info about your system such as: 
- OS version
- RAM capacity 
- Disk Space Capacity
- are you using VM/Docker/Containers

This problem also may be related to the RAM problem, when the node process doesn't have enough memory, could you check that you haven't some global options such as [--max-old-space-sizesize-in-megabytes](https://nodejs.org/api/cli.html#--max-old-space-sizesize-in-megabytes) and enough memory and disk space on your machine, this would explain the success of your pipeline on ms-hosted agents. also we upgraded task runner to [node 16 in version 1.212.0](https://github.com/microsoft/azure-pipelines-tasks/pull/16954), could you try to run it under node16.

**Comment by DmitriiBobreshev** [comment]
Hi @adurangalvis, thanks again for reporting and sorry for the delay, I'm closing the issue rn due to inactivity, please, feel free to reopen it at any time.
