### ISSUE TITLE
[BUG]: NPMv1 ##[warning]Can't find loc string for key: Info_GotAndMaskAuth

### ISSUE THREAD

**Issue by gavintoddchurch** [microsoft/azure-pipelines-tasks#20130]
### New issue checklist

- [X] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [X] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [X] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

npm

### Task version

1.241.1

### Issue Description

In the latest version of the task there is warning `##[warning]Can't find loc string for key: Info_GotAndMaskAuth`.

### Environment type (Please select at least one enviroment where you face this issue)

- [X] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 20.04

### Relevant log output

```shell
==============================================================================
Task         : npm
Description  : Install and publish npm packages, or run an npm command. Supports npmjs.com and authenticated registries like Azure Artifacts.
Version      : 1.241.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/npm
==============================================================================
##[debug]Resource Utilization warnings is disabled, switch "DISABLE_RESOURCE_UTILIZATION_WARNINGS" variable to "true" if you want to enable it
##[debug]Using node path: /agent/externals/node20_1/bin/node
##[debug]agent.TempDirectory=/agent/_work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_COMMAND
##[debug]loading INPUT_WORKINGDIR
##[debug]loading INPUT_CUSTOMCOMMAND
##[debug]loading INPUT_CUSTOMREGISTRY
##[debug]loading INPUT_PUBLISHREGISTRY
##[debug]loading INPUT_PUBLISHPACKAGEMETADATA
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 10
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : /agent/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.241.1/task.json
##[debug]adding resource file: /agent/_work/_tasks/Npm_fe47e961-9fa8-4106-8639-368c022d43ad/1.241.1/task.json
##[debug]system.culture=en-US
##[debug]Getting Packaging service access points
##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/<redacted>
##[debug]System.ServerType=Hosted
##[debug]Getting credentials for local feeds
##[debug]SYSTEMVSSCONNECTION exists true
##[warning]Can't find loc string for key: Info_GotAndMaskAuth
##[debug]Processed: ##vso[task.issue type=warning;]Can't find loc string for key: Info_GotAndMaskAuth
##[debug]Info_GotAndMaskAuth
```
```


### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>


### Repro steps

```yml
Run any npm@1 task for example
            - task: Npm@1
              displayName: Install dependencies
              inputs:
                command: ci
```

**Comment by anthonywhite** [comment]
also getting this on version `0.242.1`

**Comment by somphouang** [comment]
also getting same issue on npmAuthenticate@0 task with same setup self host 
![image](https://github.com/microsoft/azure-pipelines-tasks/assets/17149754/91bc30a1-dd57-4038-a768-7ad99e0c24d4)

**Comment by krisrm** [comment]
Same issue, npmAuthenticate@0 , 0.242.0

**Comment by ericbenhumayo** [comment]
I'm also seeing this issue with npm install version 1.241.1

**Comment by SchulteMarkus** [comment]
Related #20120

**Comment by eduardofontes** [comment]
Task         : Universal packages
Description  : Download or publish Universal Packages
Version      : 0.242.1

##[warning]Can't find loc string for key: Info_GotAndMaskAuth

##[error]Error: ENOENT: no such file or directory, chmod '/opt/hostedtoolcache/ArtifactTool/0.2.344/x64/Artifacttool'

The pipeline is broken since today.

**Comment by jonasbbernardi** [comment]
Same issue with Universal packages

**Comment by micaelvitor** [comment]
For a temporary fix just change the task version to 0.228.0

example: 

` - task: UniversalPackages@0.228.0`

**Comment by probststefan** [comment]
Does anyone have a solution to get npmAuthenticate@0 to work again?

**Comment by SchulteMarkus** [comment]
> Does anyone have a solution to get npmAuthenticate@0 to work again?

No :-(
Downgrading to npmAuthenticate@0.228.0 failed: `"A task is missing. The pipeline references a task called 'npmAuthenticate'. This usually indicates the task isn't installed, and you may be able to install it from the Marketplace: https://marketplace.visualstudio.com. (Task version 0.228.0, job 'build', step ''.)"`
In our pipeline, last working npmAuthenticate was 0.238.2. But even downgrading to 0.238.2 does not help., the following `npm ci` still fails with 401 when connecting to our private NPM registry.

**Comment by somphouang** [comment]
I am not sure if I would wait or depend on these tasks in the future.  Here is my approach that does work, I am using self-host Ubuntu agent.

```
...
          - task: NodeTool@0
            displayName: 'Use Node 18.x'
            inputs:
              versionSpec: 18.x
              checkLatest: true
          
         # Used to demo what original .npmrc looks like before we build
          - task: Bash@3
            displayName: '.npmrc before to learn'
            inputs:
              targetType: 'inline'
              script: |
                cat $(Build.SourcesDirectory)/.npmrc
          
         # Below essentially replace the npmAuthenticate where it does similarly to inject in the authToken into the .npmrc
          - task: Bash@3
            displayName: '.npmrc Add Auth'
            inputs:
              targetType: 'inline'
              script: |
                # Backup original .npmrc
                cp $(Build.SourcesDirectory)/.npmrc $(Build.SourcesDirectory)/.npmrcOrig
                # Add new line for npmrc auth
                printf "\n\n" >> $(Build.SourcesDirectory)/.npmrc
                grep "registry=*" $(Build.SourcesDirectory)/.npmrc | cut -f 2 -d '=' | tr -d ' ' | \
                echo "//$(</dev/stdin):_authToken=$(System.AccessToken)" >> $(Build.SourcesDirectory)/.npmrc
          
          # Run this to Demo what happen after authToken is added into the .npmrc looks like similar to npmAuthenticate task
          - task: Bash@3
            displayName: '.npmrc after'
            inputs:
              targetType: 'inline'
              script: |
                cat $(Build.SourcesDirectory)/.npmrc
        
          # Run "npm install" to test out if it goes to our Artifact Feed specified in the .npmrc with the proper authToken
          - task: Bash@3
            displayName: 'Install NPM'
            inputs:
              targetType: 'inline'
              script: |
                npm install
                # uncomment below if want to see verbose
                # npm install --loglevel verbose  
          
          # Cleanup the injected authToken in the .npmrc with original file, not as clean as npmAuthenticate does but works
          - task: Bash@3
            displayName: '.npmrc Removed Auth'
            inputs:
              targetType: 'inline'
              script: |
                # Backup original .npmrc
                cp $(Build.SourcesDirectory)/.npmrcOrig $(Build.SourcesDirectory)/.npmrc
                rm $(Build.SourcesDirectory)/.npmrcOrig
```

**Comment by KristofKuli** [comment]
As a workaround, you can try using the previous version, 1.238.1.
  - task: Npm@1.238.1
    inputs:
      command: 'install'

**Comment by MicroTuld** [comment]
> Task : Universal packages Description : Download or publish Universal Packages Version : 0.242.1
> 
> ##[warning]Can't find loc string for key: Info_GotAndMaskAuth
> 
> ##[error]Error: ENOENT: no such file or directory, chmod '/opt/hostedtoolcache/ArtifactTool/0.2.344/x64/Artifacttool'
> 
> The pipeline is broken since today. Don't know it is related to this issue.

Though UniversalPackagesV0 is also having these warnings, that it is breaking was due to another reason, fixed here: https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/354

**Comment by rLindorfer** [comment]
Same issue with `1.241.1`

**Comment by aarontravass** [comment]
> Same issue with `1.241.1`

Same for me as well. Node version is 20.

**Comment by tsulli** [comment]
We're seeing the same NPM warning with task version 1.241.1, agent version 3.241.0

**Comment by ganeshg2491** [comment]
We are seeing same warning with NPM@1 task (1.242.1)

This pull request indicates that the issues have been addressed, but it appears that the problem still persists.
https://github.com/microsoft/azure-pipelines-tasks-common-packages/pull/345

**Comment by GavinToddlds** [comment]
I believe they would need to deploy a new version for that to get change to get added into the task.

**Comment by mapau** [comment]
We are seeing same warning with npmAuthenticate 0.242.0 and Agent name: 'Hosted Agent' Current agent version: '3.241.0'

using npmAuthenticate@0.238.2 fix the warning output

**Comment by shiraze** [comment]
> Same issue with Universal packages

I've raised https://github.com/microsoft/azure-pipelines-tasks/issues/20203 to track Universal Packages

**Comment by GavinToddlds** [comment]
@microsoft/azure-artifacts-packages is there a plan to release a new version of the task with the fix that seems to be merged into the repo?

**Comment by pdzienisiewicz** [comment]
Will there be a fix implemented on official **npm**?
I still get an **error** when installing the latest npm `[warning]Can't find loc string for key: Info_GotAndMaskAuth` using npm install via Azure Pipelines (currently showing **1.242.1**).

**Comment by bpaithari** [comment]
> We also have this issue. Any updates?

**Comment by somphouang** [comment]
I am not sure when the update will come out, I have a successful workaround that works well for our team.  Use the known working version of the npmAuthenticate@0.238.1 to inject in the Authorization into the referenced `.npmrc` that is used in the build job run to later run `Bash@3` or can be `PowerShell@2` task running inline command like `npm install`, `npm run build`, and maybe `npm publish`.

Just need to make sure firstly install the NodeTools@0 with the version to use for the pipeline job run.

```
          ...
          - task: NodeTool@0
            displayName: 'Use Node ${{ parameters.nodeToolVer }}'
            inputs:
              versionSpec: '${{ parameters.nodeToolVer }}'
              checkLatest: true

          # Update npm Auth for Artifact Feed login
          - task: npmAuthenticate@0.238.1
            displayName: 'Authenticate Artifact Feed'
            inputs:
              workingFile: '.npmrc'

          # Using the Azure Artifact Feed specified from the ".npmrc"
          - task: Bash@3
            displayName: 'Install ${{ parameters.artifactName }}'
            inputs:
              targetType: 'inline'
              script: |
                npm install
         ...
```

**Comment by kabawa** [comment]
I have a client with same issue, please suggest a resolution here - we’re using the npm authenticate task 

  - task: npmAuthenticate@0
    inputs:
      workingFile: ${{ parameters.NPMRC_PATH }}
      customEndpoint: <endpointname>

**Comment by tintse-thxsky-MSFT** [comment]
hi all, the problem should be resolved now. Please reopen this if it happens again.

**Comment by aarontravass** [comment]
> hi all, the problem should be resolved now. Please reopen this if it happens again.

Do we need to migrate to a new version?

**Comment by bdbvb** [comment]
still happening here

**Comment by lavi09** [comment]
still happening for npm authenticate 0.242.0

**Comment by gavintoddchurch** [comment]
I think they'll have to do a new release to get the new version.

**Comment by MirKml** [comment]
It seems that @tintse-thxsky-MSFT fixed this by this one https://github.com/microsoft/azure-pipelines-tasks/pull/20259.
There is so much npm packages which are used here and there. Somebody fixes one, but it's necessary to bump others .... seems only mfst tech stuff knows the right dependencies.

Maybe "azure-pipelines-task" package is the right one, which will be later used in pipeline agent (🙏).

**Comment by tintse-thxsky-MSFT** [comment]
> still happening here

may you post your pipeline log?

**Comment by bdbvb** [comment]
> > still happening here
> 
> may you post your pipeline log?

![image](https://github.com/user-attachments/assets/45cf9eea-c69c-4201-943b-48181798e821)

![image](https://github.com/user-attachments/assets/24386b83-c7ab-4f0e-9bdb-3d4e70f9d475)

**Comment by bdbvb** [comment]
> @bdbvb @lavi09 It should be fixed now. Can you rerun the pipeline and confirm? Thankyou.

I don't see any difference when re-running. Still same warning. Do I need to update anything?

**Comment by tintse-thxsky-MSFT** [comment]
@bdbvb to clarify, you are still seeing the error in both task: npm and task: npmauthenticate, correct?

Can you rerun again and paste the log in text?  from line 2 to line 15 is good enough.


@gavintoddchurch sorry I was focusing on "npm authenticate" task, can you retry now? "npm" task should work now.

**Comment by bdbvb** [comment]
> @bdbvb to clarify, you are still seeing the error in both task: npm and task: npmauthenticate, correct?
> 
> Can you rerun again and paste the log in text? from line 2 to line 15 is good enough.
> 
> @gavintoddchurch sorry I was focusing on "npm authenticate" task, can you retry now? "npm" task should work now.

It's working OK now, for both.

![image](https://github.com/user-attachments/assets/53036e3a-eb27-4223-8991-4f39c82be2bc)

![image](https://github.com/user-attachments/assets/e84bdbba-fda3-47c2-8214-94db6b16b216)

**Comment by gavintoddchurch** [comment]
Yup i'm seeing npm is using 1.238.3 now as well, and i'm not seeing the warnings. Thank you for helping us with this @tintse-thxsky-MSFT !

**Comment by anthonywhite** [comment]
still not working here
<img width="340" alt="image" src="https://github.com/user-attachments/assets/62950fba-bb4a-44b5-9593-a121e25649ee">

**Comment by bdbvb** [comment]
I'm getting warnings again, but this time only for npm authenticate. The task version has increased to 0.243.1

![image](https://github.com/user-attachments/assets/4a7ce230-bdb2-471b-bfe9-b9376af5f041)

**Comment by lavi09** [comment]
> @bdbvb @lavi09 It should be fixed now. Can you rerun the pipeline and confirm? Thankyou.

I still see warning in npm authenticate from today's run 
![image](https://github.com/user-attachments/assets/e17451dc-f545-4ee6-929e-572a8cc2655e)

**Comment by jazelenk** [comment]
Seeing this same error with UniversalPackages@0

##[warning]Can't find loc string for key: Info_GotAndMaskAuth

**Comment by shiraze** [comment]
> Seeing this same error with UniversalPackages@0
> 
> ##[warning]Can't find loc string for key: Info_GotAndMaskAuth

See https://github.com/microsoft/azure-pipelines-tasks/issues/20203

**Comment by RickMontalvoCubero** [comment]
We started to experience the same issue with **task: UniversalPackages@0**  Are there any updates on this?

**Comment by shiraze** [comment]
> We started to experience the same issue with **task: UniversalPackages@0** Are there any updates on this?

See #20203
It is a different issue

**Comment by bdbvb** [comment]
> I'm getting warnings again, but this time only for npm authenticate. The task version has increased to 0.243.1
> 
> ![image](https://private-user-images.githubusercontent.com/11095196/356394887-4a7ce230-bdb2-471b-bfe9-b9376af5f041.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NTY4MTEsIm5iZiI6MTcyMzU1NjUxMSwicGF0aCI6Ii8xMTA5NTE5Ni8zNTYzOTQ4ODctNGE3Y2UyMzAtYmRiMi00NzFiLWJmZTktYjkzNzZhZjVmMDQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEzNDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNzc0YjQ0M2M4ZDZiZWNjODE5MzhlOWQ4MzI5NDJjYzk3MjBhMzY1NGMzNmUwNTRjYzIwNTg1OGNlN2U4ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QGNTUmvpcTKtOC-DgwCvXbUOkdIuC3q4xuE-vkGERfU)

It seems to have cleared up as of Aug 9, no more warnings (for npm or npm authenticate).

**Comment by cabralRodrigo** [comment]
Issue still present in version 1.244.1
![image](https://github.com/user-attachments/assets/1f7fcc32-08ad-4064-9fc9-d21b7bfa530e)
