### ISSUE TITLE
[BUG]: AzurePowerShell@5: Fallback to Get-LatestModuleLinux fails when version is set to "null"

### ISSUE THREAD

**Issue by pkosek** [microsoft/azure-pipelines-tasks#21143]
### New issue checklist

- [x] I searched for [existing GitHub issues](https://github.com/microsoft/azure-pipelines-tasks/issues)
- [x] I read [pipeline troubleshooting guide](https://docs.microsoft.com/vsts/build-release/actions/troubleshooting)
- [x] I checked [how to collect logs](https://learn.microsoft.com/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops)

### Task name

AzurePowerShell

### Task version

5

### Issue Description

The `AzurePowerShell@5` task fails on Linux agents when `azurePowerShellVersion` is **not specified**, due to a bug in the script logic in `Utility.ps1`.

When no version is provided in the YAML CI, the `$targetAzurePs` parameter is set to the string `"null"`, not `$null`, which causes the fallback logic to be skipped and leads to an invalid path like `/usr/share/az_null`.

This results in the following error, even when the Az module is preloaded:
```
Az version null not available locally on the agent. Downloading dynamically.
Validate-VersionParameters: Cannot convert value 'null' to type 'System.Version'.
```

### Environment type (Please select at least one enviroment where you face this issue)

- [x] Self-Hosted
- [ ] Microsoft Hosted
- [ ] VMSS Pool
- [ ] Container

### Azure DevOps Server type

dev.azure.com (formerly visualstudio.com)

### Operation system

Ubuntu 22.04

### Relevant log output

```shell
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/agent/_work/_temp/9345e305-301d-4cac-8ceb-51e68b5473a1.ps1'
File saved!
VERBOSE: Module path not present as expected in hosted agent, skipping step to make module available.
##[debug]Processed: ##vso[telemetry.publish area=TaskHub;feature=AzurePowerShellV5]{"targetAzurePs":"null","moduleSource":"privateAgent"}
VERBOSE: The value of the module path is: /usr/share/az_null
VERBOSE: No module path found with this name
VERBOSE: The updated value of the PSModulePath is: /home/AzDevOps/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
Exception: /agent/_work/_tasks/AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62/5.257.0/Utility.ps1:94
Line |
  94 |  …             throw ("Could not find the module path with given version …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find the module path with given version.

##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed
##[error]PowerShell exited with code '1'.
```

### Full task logs with system.debug enabled

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Repro steps

```yml

```

**Comment by v-vikjadhav** [comment]
Hi @pkosek thanks for opening the issue. To resolve the issue, explicitly specify the Azure PowerShell version in your pipeline YAML. You can use either the latest available version or a specific version installed on your agent.

- task: AzurePowerShell@5
  inputs:
    azureSubscription: '<your-service-connection>'
    azurePowerShellVersion: 'LatestVersion'  # or 'OtherVersion' with a specific version
    ScriptType: 'InlineScript'
    Inline: |
      # Your PowerShell commands here

This ensures the task uses a valid Az module path and avoids the fallback logic that leads to the error.

**Comment by v-vikjadhav** [comment]
@pkosek Could you please provide update on mentioned steps. Does this resolve your issue?

**Comment by v-vikjadhav** [comment]
@pkosek Does the shared steps works for you? We are awaiting response from you.

**Comment by pkosek** [comment]
I think that works. Cannot confirm as we’ve moved to RHEL. Nonetheless, there seems to be a bug in script logic so should be fixed.

**Comment by v-vikjadhav** [comment]
Closing this issue as you moved to RHEL & workaround is available. Please reopen or create the issues with us if you face any issues in future.

**Comment by jikuja** [comment]
What was the reason not to fix the actual underlying bug?

> To resolve the issue, explicitly specify the Azure PowerShell version in your pipeline YAML. You can use either the latest available version or a specific version installed on your agent.

Incompatible paramters should emit human readable error, not a generic error caused by mismatched types.


I just encountered this => Not fixed
