### ISSUE TITLE
Cannot build in VSTS - Dotnet command failed with non-zero exit code

### ISSUE THREAD

**Issue by jakubsvobodacz** [Microsoft/azure-pipelines-tasks#5094]
Without making any changes to our project files, just regular code update, our builds started to fail from this monday - 21/08/2017. During the build, in the log, we get the following error at the _Restore step_:

`Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1`

And

`Dotnet command failed with non-zero exit code on the following projects : d:\a\1\s\BD.YRD.Tests\BD.YRD.Tests.csproj`

We have not made any changes to the Tests csproj. We only tried to remove the test project just to see if it builds but then it started to throw the same error for the main web project. We use hosted2017 agent. Our .net core project is 1.1.1.

Any ideas how to solve it?

This is the output from our .net info step:

_2017-08-23T08:01:05.6316895Z ##[section]Starting: Info
2017-08-23T08:01:05.6596901Z ==============================================================================
2017-08-23T08:01:05.6596901Z Task         : .NET Core
2017-08-23T08:01:05.6606897Z Description  : Build, test and publish using dotnet core command-line.
2017-08-23T08:01:05.6606897Z Version      : 1.0.2
2017-08-23T08:01:05.6606897Z Author       : Microsoft Corporation
2017-08-23T08:01:05.6606897Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2017-08-23T08:01:05.6606897Z ==============================================================================
2017-08-23T08:01:07.3557124Z [command]"C:\Program Files\dotnet\dotnet.exe" --info d:\a\1\s\BD.YRD.Tests\BD.YRD.Tests.csproj
2017-08-23T08:01:09.3707368Z .NET Command Line Tools (2.0.0)
2017-08-23T08:01:09.3807382Z 
2017-08-23T08:01:09.3807382Z Product Information:
2017-08-23T08:01:09.3857379Z  Version:            2.0.0
2017-08-23T08:01:09.4357389Z  Commit SHA-1 hash:  cdcd1928c9
2017-08-23T08:01:09.4357389Z 
2017-08-23T08:01:09.4387377Z Runtime Environment:
2017-08-23T08:01:09.4387377Z  OS Name:     Windows
2017-08-23T08:01:09.4387377Z  OS Version:  10.0.14393
2017-08-23T08:01:09.4707381Z  OS Platform: Windows
2017-08-23T08:01:09.5137399Z  RID:         win10-x64
2017-08-23T08:01:09.5137399Z  Base Path:   C:\Program Files\dotnet\sdk\2.0.0\
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z Microsoft .NET Core Shared Framework Host
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z   Version  : 2.0.0
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5137399Z 
2017-08-23T08:01:09.5147402Z [command]"C:\Program Files\dotnet\dotnet.exe" --info d:\a\1\s\BD.YRD.Web\BD.YRD.Web.csproj
2017-08-23T08:01:09.5147402Z .NET Command Line Tools (2.0.0)
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z Product Information:
2017-08-23T08:01:09.5147402Z  Version:            2.0.0
2017-08-23T08:01:09.5147402Z  Commit SHA-1 hash:  cdcd1928c9
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z Runtime Environment:
2017-08-23T08:01:09.5147402Z  OS Name:     Windows
2017-08-23T08:01:09.5147402Z  OS Version:  10.0.14393
2017-08-23T08:01:09.5147402Z  OS Platform: Windows
2017-08-23T08:01:09.5147402Z  RID:         win10-x64
2017-08-23T08:01:09.5147402Z  Base Path:   C:\Program Files\dotnet\sdk\2.0.0\
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z Microsoft .NET Core Shared Framework Host
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z   Version  : 2.0.0
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z   Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5147402Z 
2017-08-23T08:01:09.5387414Z ##[section]Finishing: Info_

**Comment by chrisrpatterson** [comment]
Do you have a global.json in your project that locks you to a particular version of the SDK?

**Comment by jakubsvobodacz** [comment]
Hi chrisrpatterson, no we do not have global.json. Actually, that was the first thing I tried to do - adding a global.json with targetting the SDK that we use locally but that did not help, so I took it out again.

**Comment by richlander** [comment]
Can we get access to the customer's project or at least the full build log to investigate why 2.0 is failing to restore? You can send me mail at rlander@ms.

**Comment by chrisrpatterson** [comment]
@jakubsvobodacz what is your account name and what is the name of the build definition in question?

**Comment by jakubsvobodacz** [comment]
Hi both,

Our vsts is on: https://nnit-code.visualstudio.com/YardstickApp
Build definition name: `YardstickApp-ASP.NET Core-CI`

![build_definition_steps](https://user-images.githubusercontent.com/21977019/29655045-e262ec34-88af-11e7-9684-a2fd3a2978f2.PNG)
[logs_322.zip](https://github.com/Microsoft/vsts-tasks/files/1248065/logs_322.zip)

**Comment by wli3** [comment]
@jakubsvobodacz i think he means @microsoft.com

**Comment by wli3** [comment]
@jakubsvobodacz I cannot access the VSTS account, what is the target framework of your test project and the "main" project?

from the error, it could be a variation of ,
https://developercommunity.visualstudio.com/content/problem/95070/could-not-load-file-or-assembly-systemruntime-vers.html

**Comment by jakubsvobodacz** [comment]
I deleted the test project. We did not have any tests. The project was basically empty for now. the Target framework for web project is .NET Core 1.1
then we have Database project with target platform Azure SQL db V12

**Comment by wli3** [comment]
@jakubsvobodacz so the problem still persists? Or there was no test project from the beginning?
From the log, the build try to restore the test project,

```
2017-08-23T08:24:15.0811604Z [command]"C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\s\BD.YRD.Tests\BD.YRD.Tests.csproj
2017-08-23T08:24:20.0549811Z   Restoring packages for d:\a\1\s\BD.YRD.Tests\BD.YRD.Tests.csproj...
2017-08-23T08:24:20.0669831Z   Restoring packages for d:\a\1\s\BD.YRD.Web\BD.YRD.Web.csproj...
```

And then, it seems failed due to the p2p reference from the Tests.csproj to the Web.csproj
```
2017-08-23T08:25:20.8041720Z d:\a\1\s\BD.YRD.Tests\BD.YRD.Tests.csproj : error NU1105: Unable to find project information for 'd:\a\1\s\BD.YRD.Web\BD.YRD.Web.csproj'. The project file may be invalid or missing targets required for restore.
```

**Comment by jakubsvobodacz** [comment]
But we do not have any references in the csproj or I do not see any:

```<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp1.1</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId>aspnet-BD.YRD.Web-002b42cb-017c-46ce-a7e1-d5a5c37ab084</UserSecretsId>
    <WebProject_DirectoryAccessLevelKey>0</WebProject_DirectoryAccessLevelKey>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Shared\Components\**" />
    <Content Remove="Views\Shared\Components\**" />
    <EmbeddedResource Remove="Views\Shared\Components\**" />
    <None Remove="Views\Shared\Components\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.Azure.KeyVault.Core" Version="2.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.1.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.2" PrivateAssets="All" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.0" />
    <PackageReference Include="WindowsAzure.Storage" Version="8.1.4" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="BundlerMinifier.Core" Version="2.4.337" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0" />
  </ItemGroup>

</Project>```

**Comment by wli3** [comment]
@jakubsvobodacz Is this project _BD.YRD.Web.csproj_? Could you also show me _BD.YRD.Tests.csproj_? 

As the error shows, there is a file "BD.YRD.Tests\BD.YRD.Tests.csproj", if you removed the test project, could you double check if it is building the latest branch? Could you run the build again to see if it still has the error on the test project file?

Also could you try to restore both  _BD.YRD.Web.csproj_,  _BD.YRD.Tests.csproj_ and could you send the pre process log to me by build with

```
 dotnet restore BD.YRD.Tests.csproj /pp > TestsProjPreprocessResult.txt
 dotnet restore BD.YRD.Web.csproj /pp > WebProjPreprocessResult.txt
```

and send TestsProjPreprocessResult.txt and WebProjPreprocessResult.txt  to `wul` at `microsoft.com`?

**Comment by jakubsvobodacz** [comment]
Ok, we did not notice that the test project was still present in the master branch. I deleted it directly in our vsts and now the build succeeded.

**Comment by rihei** [comment]
We also had this error in VSTS today, after updating the global.json's sdk version from 1.0.0 to 1.1.0.

d:\a\1\s\src\Test\Test.csproj : error NU1105: Unable to find project information for 'd:\a\1\s\src\Web\Web.csproj'. The project file may be invalid or missing targets required for restore.

The build succeed's when I change the sdk version back to 1.0.0.
Apparently the VSTS hosted build agent doesn't have the 1.1.0 sdk installed? https://www.visualstudio.com/en-us/docs/build/concepts/agents/hosted#hosted-vs2017

**Comment by trbngr** [comment]
I'm hitting this issue as well.

For me, it seems that `BundlerMinifier.Core` is the offender. If you remove that tool, `restore` succeeds.

**Comment by darrentraffk** [comment]
After updating to .NET Core 2.0, we're experiencing the same issue on VSTS.  Any test project referencing a .NET Core app 2.0 web project fails with "error NU1105: Unable to find project information for {the web project}"  If we remove the test project, then everything builds fine on VSTS.  If we add a reference to the web project from other test files, those fail also.

**Comment by darrentraffk** [comment]
@trbngr Thanks.  This worked for me.  

For others, to be more specific, comment out:

`<DotNetCliToolReference Include="BundlerMinifier.Core" Version="X.X.XXX" />
`

The PackageReference can stay.

**Comment by verysimplenick** [comment]
Yep same with EF core
```
<DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.0" PrivateAssets="All" />
```
If I commented this line all sln build successfully. If not -> csproj builded, solution isn't.

**Comment by deanilvincent** [comment]
@verysimplenick what did you do to fix your issue? I'm having the same issue.

**Comment by singhbibek** [comment]
HI All, 
I have added the SonarQube task in my build for code analysis of .NetCore task, and its start falling since i added the SonarQube, when i am disabling the SonarQubethan its building else throughing error , below is the error-

Time Elapsed 00:00:04.04
2017-11-20T09:20:11.9948934Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
2017-11-20T09:20:11.9961930Z [command]"C:\Program Files\dotnet\dotnet.exe" build d:\a\1\s\Microsoft.Procurement.PurchaseOrderValidator\Microsoft.Procurement.Validators.Tests\Microsoft.Procurement.Validators.Tests.csproj /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation=d:\a\1\a\WebApp.zip /p:DeployIisAppPath=direct
2017-11-20T09:20:14.5701747Z Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
2017-11-20T09:20:14.5701747Z Copyright (C) Microsoft Corporation. All rights reserved.
2017-11-20T09:20:14.5701747Z 
2017-11-20T09:20:17.8759397Z d:\a\1\.sonarqube\bin\targets\SonarQube.Integration.targets(165,5): error MSB4062: The "IsTestFileByName" task could not be loaded from the assembly d:\a\1\.sonarqube\bin\SonarQube.Integration.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [d:\a\1\s\Microsoft.Procurement.PurchaseOrderValidator\Microsoft.Procurement.PurchaseOrderValidator.Infrastructure\Microsoft.Procurement.PurchaseOrderValidator.Infrastructure.csproj]
2017-11-20T09:20:20.9121442Z 
2017-11-20T09:20:20.9301436Z Build FAILED.
2017-11-20T09:20:20.9301436Z 
2017-11-20T09:20:20.9321448Z d:\a\1\.sonarqube\bin\targets\SonarQube.Integration.targets(165,5): error MSB4062: The "IsTestFileByName" task could not be loaded from the assembly d:\a\1\.sonarqube\bin\SonarQube.Integration.Tasks.dll. Could not load file or assembly 'Microsoft.Build.Utilities.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. [d:\a\1\s\Microsoft.Procurement.PurchaseOrderValidator\Microsoft.Procurement.PurchaseOrderValidator.Infrastructure\Microsoft.Procurement.PurchaseOrderValidator.Infrastructure.csproj]
2017-11-20T09:20:20.9331460Z 0 Warning(s)
2017-11-20T09:20:20.9331460Z 1 Error(s)
2017-11-20T09:20:20.9331460Z

**Comment by bryanmacfarlane** [comment]
@singhbibek - create a new issue

**Comment by verysimplenick** [comment]
@deanilvincent , yes fixed in nuget https://github.com/NuGet/Home/issues/5941

**Comment by lincolnzocateli** [comment]
Guys, I was having the same problem reported by jakubsvobodacz, but I managed to succeed in the build with a combination of adjustments, which I share with you:

1. My csproj (not test)
```
  <ItemGroup>
    <PackageReference Include = "Microsoft.AspNetCore.All" Version = "2.0.3" />
       <! - <PackageReference Include = "Microsoft.NETCore.App" Version = "2.0.4" /> ->
  </ ItemGroup>
```

2. My csproj test project (XUnit)
```
<Project Sdk = "Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework> netcoreapp2.0 </ TargetFramework>
    <IsPackable> false </ IsPackable>
    <RuntimeFrameworkVersion> 2.0.3 </ RuntimeFrameworkVersion>
  </ PropertyGroup>
  <PropertyGroup>
    <LangVersion> latest </ LangVersion>
  </ PropertyGroup>
  <ItemGroup>
    <PackageReference Include = "Microsoft.AspNetCore.All" Version = "2.0.3" />
    <PackageReference Include = "Microsoft.NET.Test.Sdk" Version = "15.5.0" />
    **<! - <PackageReference Include = "Microsoft.NETCore.App" Version = "2.0.4" /> ->**
    <PackageReference Include = "Moq" Version = "4.7.145" />
    <PackageReference Include = "xunit" Version = "2.3.1" />
    <PackageReference Include = "xunit.runner.visualstudio" Version = "2.3.1" />
  </ ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include = "dotnet-xunit" Version = "2.3.1" />
  </ ItemGroup>
</ Project>

```
3. And most importantly, **when I removed the global.json** file that forced SDK 2.1.3, the build ran without any problems.
```
{
   "projects": ["src", "tst"],
   "sdk": {
     "version": "2.1.3"
   }
}
```

**Comment by Amit-Kumar-Sonkar** [comment]
ITS REALLY .. fed up of this error what need to do .. tried in multiple ways now with the help of some solutions given here by various guys.. let see trying ..

now this is the last error what we all were facing.... by the way these vedio helped me but still facing ERROR


Error: C:\hostedtoolcache\windows\dncs\1.0.4\x64\dotnet.exe failed with return code: 1
Dotnet command failed with non-zero exit code on the following projects : D:\a\3\s\PMSite.csproj
---------------------------------------------------

https://docs.microsoft.com/en-us/vsts/pipelines/languages/dotnet-core?view=vsts&tabs=designer

**Comment by devTimmy** [comment]
Apparently, adding a **Nuget Restore** task before **.NET Core Restore** worked for me.

**Comment by moswald** [comment]
Closing as this is not a Tasks issue. There are fixes to apply to the csproj files to resolve the errors.
