### ISSUE TITLE
Xcode builds suddenly failing with message 'error: <pod> does not support provisioning profiles

### ISSUE THREAD

**Issue by christoferlof** [Microsoft/azure-pipelines-tasks#9984]
**Question, Bug, or Feature?**  
*Type*: Bug

**Enter Task Name**: Xcode@5  

## Environment
- Azure Pipelines
- Hosted Agent

## Issue Description
iOS Swift app with some external CocoaPods dependencies. Built fine for weeks, since March 28th (CET) suddenly failing with error code 65. 

```error: <podname> does not support provisioning profiles. <podname> does not support provisioning profiles but provisioning profile <distrprofile> has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor. (in target '<podname>')```

Changing provisioning mode to "Automatic" doesn't resolve it as suggested.

Builds that passed on or before March 27th are now failing when resubmitted.
![image](https://user-images.githubusercontent.com/166592/55291252-d69c7880-53dc-11e9-82f1-78fa2f9029ee.png)

[Update to task-lib 2.8.0 in tasks using iOS signing and secure files](https://github.com/Microsoft/azure-pipelines-tasks/commit/1b019b9f65202d65ac58150bff6514938b53ff78) was merged to master on the 27th. Coincidence?  

## Error logs
https://developercommunity.visualstudio.com/content/problem/508973/xcode-builds-suddenly-failing-with-message-error-d.html

**Comment by DavidStaheli** [comment]
Thanks for reporting this @christoferlof.  You reached the right people and we're investigating ASAP.

**Comment by jboisjo** [comment]
Same issue for us!

**Comment by madhurig** [comment]
The update to the task-lib 2.8.0 hasn't deployed yet, so that is unrelated. We are investigating. Thanks for reporting the issue.

**Comment by maximeferron** [comment]
Same thing for us at CAE pipelines, pipeline error with the same behaviour

**Comment by DavidStaheli** [comment]
We're investigating whether this could be caused by rolling out the latest version of CocoaPods last week. We're trying to reproduce the error.  Can someone please run this script as part of their pipeline to see if rolling back to a previous version of CocoaPods patches the problem?
```bash
echo "uninstalling all cocoapods versions"
sudo gem uninstall cocoapods -ax
echo "installing cocoapods version 1.5.3"
sudo gem install cocoapods -v 1.5.3
```

**Comment by tigran-stdev** [comment]
@DavidStaheli Hi, I have just tried to rolling back to 1.5.3 version of CocoaPods as you requested and seems it solved the issue in my pipeline.

**Comment by christoferlof** [comment]
@DavidStaheli confirmed. We now have green builds again 👍

Downgrading CocoaPods fixes the problem

**Comment by tmzblue** [comment]
@DavidStaheli we were struggling with this since the beggining of the month, now everything is green again ✔. Thanks a lot.

**Comment by hugo-retro** [comment]
@DavidStaheli We are coming at an awkward point. Currently busy moving over our apps to azure pipeline. Our react native ios based one builds funnily enough without issue. But our pure swift one does not. Cocoapods 1.5.3 makes no difference.

**Comment by hugo-retro** [comment]
Found a solution to our project. First, ensure you pod file has the following post-install section:

`
platform :ios, '9.0'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

#--- This was what we had missing ---
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end


target <your project> do
  <your pods>
end
`

Next we used the latest cocoapods version which worked (1.7.0.beta.3). So have this as a script before the build process:
`
echo "uninstalling all cocoapods versions"
sudo gem uninstall cocoapods -ax
echo "installing cocoapods version latest"
sudo gem install cocoapods --pre
`

**Comment by madhurig** [comment]
Thanks for reporting the issue and providing your solutions. We are closing this issue since it is resolved. We are looking into better ways to providing this integration with CocoaPods and signing as a future enhancement.

**Comment by EddieLukeAtmey** [comment]
Hi, this doesn't help me if my pods are in repo. I've tried your suggest and write `post_install` script, run `pod install` locally and pushed the update (code_signing_required = NO) to repo. Still failure with the same message. 

What should I do now? In pipeline, because pods are in repo so I've changed the default setting in `xcode build` to my custom workspace: `$(projectName).xcworkspace`.

**Comment by esunilkumare** [comment]
@hugo-retro Your solution helped me solve same issue on an Ionic iOS build created from Azure Build Pipelines

**Comment by J-Graham** [comment]
@esunilkumare Can you maybe mention how you updated the PodFile? We are adding the platform and building in a CommandLine script step. Do you just modify it as part of the pipline?

**Comment by chimeraTrijay** [comment]
> Found a solution to our project. First, ensure you pod file has the following post-install section:
> 
> ```
> platform :ios, '9.0'
> 
> # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
> use_frameworks!
> 
> #--- This was what we had missing ---
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
>       config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
>       config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
>     end
>   end
> end
> 
> 
> target <your project> do
>   <your pods>
> end
> ```
> 
> Next we used the latest cocoapods version which worked (1.7.0.beta.3). So have this as a script before the build process:
> 
> ```
> echo "uninstalling all cocoapods versions"
> sudo gem uninstall cocoapods -ax
> echo "installing cocoapods version latest"
> sudo gem install cocoapods --pre
> ```

how do I add this in my pod file, it is not in my directory, and if it is created after run time how do I create it after installation in azure devops

**Comment by Juandi-M** [comment]
> > Found a solution to our project. First, ensure you pod file has the following post-install section:
> > ```
> > platform :ios, '9.0'
> > 
> > # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
> > use_frameworks!
> > 
> > #--- This was what we had missing ---
> > post_install do |installer|
> >   installer.pods_project.targets.each do |target|
> >     target.build_configurations.each do |config|
> >       config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
> >       config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
> >       config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
> >     end
> >   end
> > end
> > 
> > 
> > target <your project> do
> >   <your pods>
> > end
> > ```
> > 
> > 
> > Next we used the latest cocoapods version which worked (1.7.0.beta.3). So have this as a script before the build process:
> > ```
> > echo "uninstalling all cocoapods versions"
> > sudo gem uninstall cocoapods -ax
> > echo "installing cocoapods version latest"
> > sudo gem install cocoapods --pre
> > ```
> 
> how do I add this in my pod file, it is not in my directory, and if it is created after run time how do I create it after installation in azure devops

This is a really elegant solution for this and other projects. Thanks!

**Comment by Juandi-M** [comment]
> Found a solution to our project. First, ensure you pod file has the following post-install section:
> 
> ```
> platform :ios, '9.0'
> 
> # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
> use_frameworks!
> 
> #--- This was what we had missing ---
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
>       config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
>       config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
>     end
>   end
> end
> 
> 
> target <your project> do
>   <your pods>
> end
> ```
> 
> Next we used the latest cocoapods version which worked (1.7.0.beta.3). So have this as a script before the build process:
> 
> ```
> echo "uninstalling all cocoapods versions"
> sudo gem uninstall cocoapods -ax
> echo "installing cocoapods version latest"
> sudo gem install cocoapods --pre
> ```

The real and elegant solution for this and other projects.

**Comment by Carolhaha** [comment]
@davidstaheli @hugo-retro Hi, I tried both solutions, but all these two will stuck in the uninstalling step without moving on, are there anything else I need to take care to make sure it keep going?
![Capture1](https://user-images.githubusercontent.com/32686035/102261714-0dcbf980-3ee0-11eb-934e-d3350df745a4.PNG)
![Capture2](https://user-images.githubusercontent.com/32686035/102261720-0f95bd00-3ee0-11eb-9f3b-d5bcbe44cc5b.PNG)

**Comment by anupam99** [comment]
This worked for me. In my case, the Podfile was generated as part of azure devops pipeline build. 

So i used a PowerShell task, (before my XCode task) that inserted the missing code signing exclusions.
Here's the script for anyone trying to make these changes in pipeline. ( your file paths may differ)

```
$PodPath = "$(System.DefaultWorkingDirectory)/ios/App/Podfile"
$PodUpdatedPath = "$(System.DefaultWorkingDirectory)/ios/App/Podfile.updated"

Get-Content $PodPath | ForEach-Object {$_ -Replace 'use_frameworks!', "use_frameworks!`n`npost_install do |installer|`n  installer.pods_project.targets.each do |target|`n    target.build_configurations.each do |config|`n      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = `"`"`n      config.build_settings['CODE_SIGNING_REQUIRED'] = `"NO`"`n      config.build_settings['CODE_SIGNING_ALLOWED'] = `"NO`"`n    end`n  end`nend"} | Set-Content $PodUpdatedPath;

Get-Content $PodUpdatedPath | Set-Content $PodPath
```

**Comment by mvacha** [comment]
If you need some targets to be signed but not the rest, you can specify them this way:

```
signed_targets = ['Flutter']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if !signed_targets.include?(target.name)
      target.build_configurations.each do |config|
        puts "SET #{target.name}-#{config.name} NO SIGN"
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
end
```

**Comment by abnersouza** [comment]
> If you need some targets to be signed but not the rest, you can specify them this way:
> 
> ```
> signed_targets = ['Flutter']
> 
> post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     if !signed_targets.include?(target.name)
>       target.build_configurations.each do |config|
>         puts "SET #{target.name}-#{config.name} NO SIGN"
>         config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
>         config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
>         config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
>       end
>     end
>   end
> end
> ```

Solve my issue with Angular App with Capacitor.

**Comment by sikemullivan** [comment]
For anyone working with NativeScript and macOS-11, I found that you can't uninstall cocoapods and downgrade it to a lower version. The Podfile isn't provisioned until after you run a build at least once. Then you can replace that Podfile with your own. 

Azure Pipeline
```
pool:
  vmImage: 'macOS-11'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.16.1'
  displayName: 'Install Node.js'

- task: DownloadSecureFile@1
  name: releaseJksFile
  displayName: 'download android keystore file'
  inputs:
    secureFile: 'release.jks'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: AppleCertificate.p12
    certPwd: $(AppleCertificatePassword)
    keychain: 'temp'
    deleteCert: true
  displayName: Install Apple Certificate

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'AppleReleaseProfile.mobileprovision'
    removeProfile: true
  displayName: 'Install Apple Provisioning Profile'

# Optional... was running into build issues with latest version
#downgrading cocoapods version
- script: |
    $ANDROID_HOME/tools/bin/sdkmanager --uninstall 'build-tools;31.0.0'
  displayName: 'Remove Android 31 SDK' 

- script: |
    pip install six
    npm install -g @angular/cli nativescript
    tns clean
    npm install
    mkdir $(Build.ArtifactStagingDirectory)/android
    mkdir $(Build.ArtifactStagingDirectory)/iphoneos
    sed -i -e 's/1.00000000.00/1.$(Build.BuildNumber)/g' App_Resources/iOS/Info.plist
    sed -i -e 's/1000000/10$(Build.BuildId)/g' App_Resources/Android/src/main/AndroidManifest.xml
    sed -i -e 's/1.00000000.00/1.$(Build.BuildNumber)/g' App_Resources/Android/src/main/AndroidManifest.xml
    tns build android --env.production --release --key-store-path '$(releaseJksFile.secureFilePath)' --key-store-password '$(KeyStorePassword)' --key-store-alias '$(KeyAlias)' --key-store-alias-password '$(KeyPassword)' --bundle 
    cp -rf "platforms/android/app/build/outputs/apk/release/" "$(Build.ArtifactStagingDirectory)/android"

    echo "uninstalling all cocoapods versions"
    sudo gem uninstall cocoapods -ax
    echo "installing cocoapods version latest"
    sudo gem install cocoapods
    tns run ios --provision     #see what provisioning profile and certificate are installed... helpful for debugging
    tns build ios #creates podfile we are going to replace
    cp -rf Podfile platforms/ios/Podfile
    rm platforms/ios/Podfile.lock
    cd platforms/ios
    pod install
    cd ../../
    tns build ios --env.production --release --bundle    #creates xcworkspace
  displayName: 'Setup/Build'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 's'
    sdk: 'iphoneos'
    configuration: 'Release'
    exportPath: '$(Build.ArtifactStagingDirectory)/iphoneos/'
    packageApp: true
    xcWorkspacePath: 'platforms/ios/s.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    signingOption: 'manual'
    signingIdentity: '$(AppleCertificateSigningIdentity)'
    provisioningProfileUuid: '$(AppleProvisioningProfileUuid)'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
```

Podfile
```
use_frameworks!

target "s" do
# Begin Podfile - /Users/runner/work/1/s/node_modules/@nativescript/secure-storage/platforms/ios/Podfile
pod 'SAMKeychain', '~> 1.5.3'
# End Podfile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
  post_installNativeScript_CLI_Architecture_Exclusions_0 installer
end

# Begin Podfile - /Users/runner/work/1/s/platforms/ios/Podfile-exclusions
def post_installNativeScript_CLI_Architecture_Exclusions_0 (installer)
  installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete "VALID_ARCHS"
    config.build_settings["EXCLUDED_ARCHS_x86_64"] = "arm64 arm64e"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386 armv6 armv7 armv7s armv8 $(EXCLUDED_ARCHS_$(NATIVE_ARCH_64_BIT))"
    config.build_settings["EXCLUDED_ARCHS[sdk=iphoneos*]"] = "i386 armv6 armv7 armv7s armv8 x86_64"
  end
end
# End Podfile
end

```

**Comment by oguzhanogreden** [comment]
Thanks everyone for the helpful code excerpts.

I wanted to insert the required bit (as noted by @hugo-retro) during the build. Here's what I've used (thank you @LozanoMatheus for your patience in explaining the intricacies of `echo` 🙌 ).

I've added this as a bash script step, just before `pod install`:

```sh

podfile_path='$(System.ArtifactsDirectory)/build-artifacts/ios/App/Podfile' # You probably want to adjust this

install_line=$(grep -Fn 'install!' $podfile_path | cut -d: -f 1)
insert_at_line=$(( $install_line + 1))

part_1=$(cat $podfile_path | tail -n +1 | head -n $(($install_line)) )
part_3=$(cat $podfile_path | tail -n +$(($insert_at_line+1)) )

# https://github.com/Microsoft/azure-pipelines-tasks/issues/9984#issuecomment-483968562
part_2="post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = \"\"
      config.build_settings['CODE_SIGNING_REQUIRED'] = \"NO\"
      config.build_settings['CODE_SIGNING_ALLOWED'] = \"NO\"
    end
  end
end"

echo "$part_1" > $podfile_path
echo -e "\n#BEGIN - Inserted during the pipeline:\n" >> $podfile_path
echo "$part_2" >> $podfile_path
echo -e "\n#END - Inserted during the pipeline:\n" >> $podfile_path
echo "$part_3" >> $podfile_path
```

**Comment by attiqmscs004** [comment]
> 

Thanks for the solution. I updated my Podfile with the content provided by you but I am getting this error now.

```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.Fi5lKu/flutter_ios_build_temp_dirScZJa1/temporary_xcresult_bundle

    In file included from /Users/runner/hostedtoolcache/Flutter/2.10.2-stable/macos/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/ios/Classes/JavaScriptChannelHandler.m:5:
    /Users/runner/hostedtoolcache/Flutter/2.10.2-stable/macos/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/ios/Classes/JavaScriptChannelHandler.h:5:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Comment by billnbell** [comment]
Personally? Turn off Flutter.

**Comment by KevinRohn** [comment]
> Thanks everyone for the helpful code excerpts.
> 
> I wanted to modify the Podfile during the build. In order to make the changes @hugo-retro noted, I've used the script below (thank you @LozanoMatheus for your patience in explaining the intricacies of `echo` 🙌 ). I've added this as a bash script step, just before `pod install`.
> 
> ```shell
> podfile_path='$(System.ArtifactsDirectory)/build-artifacts/ios/App/Podfile' # You probably want to adjust this
> 
> install_line=$(grep -Fn 'install!' $podfile_path | cut -d: -f 1)
> insert_at_line=$(( $install_line + 1))
> 
> part_1=$(cat $podfile_path | tail -n +1 | head -n $(($install_line)) )
> part_3=$(cat $podfile_path | tail -n +$(($insert_at_line+1)) )
> 
> # https://github.com/Microsoft/azure-pipelines-tasks/issues/9984#issuecomment-483968562
> part_2="post_install do |installer|
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = \"\"
>       config.build_settings['CODE_SIGNING_REQUIRED'] = \"NO\"
>       config.build_settings['CODE_SIGNING_ALLOWED'] = \"NO\"
>     end
>   end
> end"
> 
> echo "$part_1" > $podfile_path
> echo -e "\n#BEGIN - Inserted during the pipeline:\n" >> $podfile_path
> echo "$part_2" >> $podfile_path
> echo -e "\n#END - Inserted during the pipeline:\n" >> $podfile_path
> echo "$part_3" >> $podfile_path
> ```

I changed the script to make sure already existing post_install entries will be kept:

```
#!/bin/bash

podfile_path="Podfile"
temp_podfile_path="Podfile.tmp"

inside_post_install=0

while IFS= read -r line; do
  if [[ "$line" == "post_install do |installer|" ]]; then
    inside_post_install=1
  fi

  if [[ "$inside_post_install" -eq 1 && "$line" == "end" ]]; then
    echo "  # Inserted during the pipeline"
    echo "  installer.pods_project.targets.each do |target|"
    echo "    target.build_configurations.each do |config|"
    echo "      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = \"\""
    echo "      config.build_settings['CODE_SIGNING_REQUIRED'] = \"NO\""
    echo "      config.build_settings['CODE_SIGNING_ALLOWED'] = \"NO\""
    echo "    end"
    echo "  end"
    echo "  # End of inserted block"
    inside_post_install=0
  fi

  echo "$line"
done < "$podfile_path" > "$temp_podfile_path"

mv "$temp_podfile_path" "$podfile_path"

```

**Comment by riethmue** [comment]
This issue was still occurring for me and @KevinRohn fix worked!

**Comment by tmezzena** [comment]
This issue was still occurring on Quasar - Capacitor 6 mode. @KevinRohn fix worked!
